### ISSUE TITLE
spec van documents object in patch .../associations/{associationId} is nog niet op orde.

### ISSUE THREAD

**Issue by rrutte** [NetwerkExamineringDigitalisering/NED-OOAPI#100]
.. en verwijst vanuit https://netwerkexamineringdigitalisering.github.io/NED-OOAPI/specification/v5/docs.html#tag/associations/operation/partialUpdateAssociationById naar flow 4, terwijl deze voor een association naar flow 3 moet verwijzen.

**Comment by rrutte** [comment]
@hamrt nog een extra opmerking. we hebben afgesproken dat we bij patch associations en offerings altijd de associationtype/offeringtype zouden meegeven. Kan je die ook in flow 2 toevoegen?

**Comment by hamrt** [comment]
fixed in #102
