### ISSUE TITLE
Attributen members en participatesIn ontbreken bij Group

### ISSUE THREAD

**Issue by JosVanderArend** [NetwerkExamineringDigitalisering/NED-OOAPI#101]
In het [OOAPI model](https://openonderwijsapi.nl/specification/v5/OOAPIv5_model.png) heeft object Group als laatste attributen members (Person[]) en participatesIn (Offering[]).
Deze attributen ontbreken echter in de OAS-definities van OOAPI, zie https://openonderwijsapi.nl/specification/v5/docs.html#tag/group_model.

Deze attributen ontbreken in de beschrijving van onze flow 1 en in het specificatiedocument. En ontbreken ook in de OAS-definities van OKE (zie https://openonderwijsapi.nl/specification/v5/docs.html#tag/group_model).

Wij hebben in elk geval het attribuut members nodig om de studenten en medewerkers te koppelen aan deze groep. En wellicht ook participatesIn om te verwijzen naar de betreffende Planbare toets (ComponentOffering).

**Comment by hamrt** [comment]
@hamrt Toevoegen aan de flow 1

**Comment by hamrt** [comment]
opgenomen in 0.9.3
