### ISSUE TITLE
naming convention consumer

### ISSUE THREAD

**Issue by rrutte** [NetwerkExamineringDigitalisering/NED-OOAPI#103]
Vanuit tests tussen Osiris en OnTrac lopen we ertegenaan dat de NL-TEST-ADMIN niet de naming convention van de bestaande consumers volgt (rio, eduxchange). @hamrt , zijn er richtlijnen tav de naamgeving. Kan ze nl. niet vinden op openonderwijs.nl.

**Comment by hamrt** [comment]
Kun je dit vraagstuk iets verder toelichten. Welk onderdeel mis je hier in? In principe wordt voor de consumer een naam gekozen voor het project waarvoor de betreffende consumer va toepassing is. Deze benaming is redelijk vrij.

**Comment by rrutte** [comment]
@hamrt We zien dat in communicatie dat er hoofdletters gebruikt wordt, maar dat er in de swagger van diezelfde consumers alleen lowercase varianten staan. bv. eduxchange

**Comment by hamrt** [comment]
We gaan alles in lower case door voeren vanaf de volgende versie. oke moet ook toegevoegd worden aan de consumer repository.  Moet opgenomen worden in de repository.
