### ISSUE TITLE
Aanpak van versioning

### ISSUE THREAD

**Issue by hamrt** [NetwerkExamineringDigitalisering/NED-OOAPI#108]
Hoe zien we voor nu de oplossing om verder te werken aan de OKE versie. 
We hebben nu twee opties:
1. Willen we de versie met 1 nummer ophogen om zo ook de aangepaste enumerations te kunnen valideren, 
2. of gaan we de aanpassingen die we nu toegevoegd hebben onderbrengen in consumers.

**Comment by hamrt** [comment]
part of #104

**Comment by hamrt** [comment]
Opnemen met project management over hoe we de release cycles zijn @hamrt  (doorzeten naar Ruud)

**Comment by JosVanderArend** [comment]
Ter informatie, document "1EdTech Versioning Framework", zie: https://www.imsglobal.org/spec/versioning/v1

**Comment by JosVanderArend** [comment]
Kan worden afgesloten
