### ISSUE TITLE
Flow 3&4 zsm conform standaard vanuit Remindo

### ISSUE THREAD

**Issue by rrutte** [NetwerkExamineringDigitalisering/NED-OOAPI#109]
Voor validatie van flows 3 en 4 hebben we vanuit Xebic ZSM conform standaard nodig dus inclusief offeringType en associationType. Paragin is klaar, alleen Eduarte nog niet. Hoe gaan we om met dit issue en komende issues als we tijdens pilot 2 en 3 tegen nieuwe standaard issues aanlopen?

**Comment by hamrt** [comment]
Opgenomen als agendapunt voor werkgroep
