### ISSUE TITLE
Aanpassing hulpmiddelen lijst in flow 1

### ISSUE THREAD

**Issue by hamrt** [NetwerkExamineringDigitalisering/NED-OOAPI#110]
Er is toch een noodzaak om extra informatie aan te leveren mbt de hulpmiddelen. De hulpmiddelen kunnen verschillen per type toets echter deze gegevens zitten nu niet in het persoons object (bijvoorbeeld extra tijd voor rekenen, en extra tijd voor taal). we kennen nu alleen extra tijd.  Hiervoor moeten we onderzoeken welke codes we mee kunnen geven voor de extra hulpmiddelen (extra tijd) per soort behoefte.  e.g. extra rekentijd extra leestijd

**Comment by hamrt** [comment]
Aanpassing nodig op NL-TEST-ADMIN-Person:
Check hoe we extra time weer geven we willen GEEN gebruik maken van een enum op dit vlak. Wel zouden een object kunnen maken met daarin de code en de omschrijving, startdatum en einddatum van de personalNeeds.
Op de person kunnen we de personalNeeds vervangen door een betere term

**Comment by roelgrif** [comment]
Ik was er niet bij dinsdag, dat weet ik, maar zou iemand toch de moeite kunnen doen om uit te leggen wat hier precies voorgesteld wordt (hoe object, waar) en waarom?

**Comment by rrutte** [comment]
Hoi Roel,

Tijdens de PeopleSoft - OnTrac testdag zijn we erachter gekomen dat de wijze waarop we personal needs hebben gemodelleerd op de componentOfferingAssociation (zowel flow 1 als 2) goed werkt.

Echter de personal needs zoals die in flow 1 bij de person (student) worden doorgegeven past niet bij de wijze waarop sis'en momenteel personal needs/hulpmiddelen/voorzieningen bij studenten administreren.

Effectief mist de toetsplanning context op het moment dat de voorzieningen zoals vastgelegd in willekeurig welk sis met code en omschrijving de context waarbinnen de personal needs zijn toegekend.

Daarom hebben we ervoor gekozen om in flow 1 (person) geen gebruik te maken van de enum, maar een lijst met objecten door te laten geven met daarin de gebruikte code, omschrijving en start/einddatums van toekenning.




Met vriendelijke groet,



René Rutte
Business Architect



MOBIEL +31 (0) 6 1370 2844









________________________________

**Comment by roelgrif** [comment]
Welke codes moeten we dan uit kiezen? Zijn dit per applicatie verschillende codes? Dat lijkt me wel wat jammer, dat we dit niet universeel houden. Kun je voorbeelden geven van codes en omschrijving ervan?

**Comment by rrutte** [comment]
Tijdens het overleg hebben we het kort gehad over standaardisering, maar daarvoor zouden alle scholen in ieder geval in NL een standaard codering moeten gaan volgen voor bijvoorbeeld ExtraTijdAlleenVoorRekenen25%, ExtraTijdAlleenVoorRekenenHalfUur, ExtraTijdBijDigitaleToetsen25%. Omdat we dat voorlopig als onhaalbaar achten hebben we voorgesteld om de codes die de individuele scholen in hun eigenSIS'en gebruiken hier toe te passen

**Comment by roelgrif** [comment]
Ja, maar de vertaalslag zal toch *ergens* moeten plaatsvinden. Met deze keuze verschuif je de beslissing van SIS / koppelvlak 1 naar het TPS. Die zal dus voor elke instelling een vertaalslag moeten gaan maken naar de eigen interne codes (b.v. binnen OnTrac) en dan ook nog een vertaalslag naar TAS. Misschien dat sommige leveranciers de gebruikte codes voorschrijven, dat zou schelen maar dat doen wij i.i.g. niet. Dus hebben wij 2 scholen in de OOAPI koppeling, dan zijn dat ook 2 verschillende setjes met codes. Waarbij het TPS dan bij elke instelling apart moet gaan interpreteren (ik weet dat er een omschrijving bij de code voorzien is maar dan nog). Volgens mij krijgen we hier op den duur enorme spijt van. Standaardisering in de in het SIS gebruikte codes is bovendien helemaal niet nodig. Als er maar een mapping komt met landelijk vastgestelde waarden, ook daar mag het TPS zelf de codes voor het pakket intern bij bedenken.

**Comment by hamrt** [comment]
Aanpassing nodig op NL-TEST-ADMIN-Person:
Check hoe we extra time weer geven we willen GEEN gebruik maken van een enum op dit vlak. Wel zouden een object kunnen maken met daarin de code en de omschrijving, startdatum en einddatum van de personalNeeds.
Op de person kunnen we de personalNeeds vervangen door een betere term 
meenemen in 0.9.3
assignedNeeds als betere term

**Comment by roelgrif** [comment]
Ik kon er gisteren helaas opnieuw niet bij zijn, maar is er iets gedaan met mijn feedback?

**Comment by hamrt** [comment]
Wordt meegenomen naar College voor Toetsting en Examinering en naar werkgroep
