### ISSUE TITLE
spec ooapi assocation/url niet compleet

### ISSUE THREAD

**Issue by rrutte** [NetwerkExamineringDigitalisering/NED-OOAPI#111]
https://netwerkexamineringdigitalisering.github.io/NED-OOAPI/specification/v5/docs.html#tag/associations/operation/listAssociationUrl

Beschrijving body is niet conform spec

**Comment by hamrt** [comment]
What would you propose? It should be the url of this association that gets returned.

**Comment by rrutte** [comment]
@hamrt  Laat maar. Week ziek geweest en dacht verschillen te zien tussen Remindo implementatie en Github. Ik sluit dit issue weer

**Comment by rrutte** [comment]
close
