### ISSUE TITLE
Waar is GET /associations/{associationId}/url voor bedoeld?

### ISSUE THREAD

**Issue by JosVanderArend** [NetwerkExamineringDigitalisering/NED-OOAPI#113]
Ik zie in de OAS het endpoint GET /associations/{associationId}/url, zie https://netwerkexamineringdigitalisering.github.io/NED-OOAPI/specification/v5/docs.html#tag/associations/operation/replaceAssociationById
Dit endpoint staat niet in het specificatiedocument en niet in de flows gedefinieerd. De operatie wordt gedefinieerd als "Get the URL of an association". Dit antwoord lijkt me vrij triviaal: {base-url}/associations/{associationId}.

Is dit een fout of wordt echt dit gebruikt? 
En, als het in gebruik is: Gaat dit om het StartUpUrl? Is dit voor flow 2? Ook voor flow 1?

**Comment by hamrt** [comment]
Nee, is bedoeld om de applicatie op te kunnen starten (ter verbetering in flow 2 op genomen) Dit zou een bericht moeten zijn vanuit toetsafname richting toetsplanning om aan te geven welke URL gebruikt kan worden om de specifieke toets voor de specifieke student klaar te zetten. (dit zouden overigens meerdere keren dezelfde URL kunnen zijn...)
@rrutte @boerrookhuiszen betekent dit volgens jullie ook dat er hier een PATCH voor zou moeten zijn in flow 2? mogelijk een die specifiek alleen de URL doorgeeft richting toetsplanning?

**Comment by rrutte** [comment]
Deze wordt idd gebruikt en dient een GET te zijn omdat de URL maar kortstondig leeft en bedoeld is voor de student om TAS op te starten vanuit TPS om een toets te kunnen maken in TAS.

De GET doet hier zijn werk al. Een Patch lijkt momenteel niet echt noodzakelijk, mede door de korte tijd dat de URL geldig is.

**Comment by hamrt** [comment]
Dit zou dus betekenen dat startUpURL niet meer nodig is in de consumer (immers de TPS heeft geen weet van deze code en kan hem ook niet mee sturen). Voorstel om deze weg te halen uit de consumer? 
Het aparte endpoint GET /associations/{associationId}/url blijft natuurlijk wel bestaan en kan door TPS aangeroepen worden om de URL op te vragen bij het TAS.

**Comment by rrutte** [comment]
@hamrt Klinkt goed. In de praktijk is de URL maar heel beperkte tijd geldig en word de GET .../url just in time aangeroepen. Wat mij betreft mag hij dus uit het consumer object.

**Comment by hamrt** [comment]
@ hamrt doorvoeren en sluiten
