### ISSUE TITLE
GET /organizations/{organizationId}

### ISSUE THREAD

**Issue by JosVanderArend** [NetwerkExamineringDigitalisering/NED-OOAPI#114]
Ik zie in de YAML ook de definitie van endpoint GET /organizations/{organizationId}.
Dit endpoint verschijnt alleen niet in de Github-specificatie-docs: https://netwerkexamineringdigitalisering.github.io/NED-OOAPI/specification/v5/docs.html 

In de flow beschrijvingen komt dit endpoint echter niet voor. Is dit voor flow 1 en/of flow 2?
In flow 2 beschrijving staat wel "ADD organization".

**Comment by hamrt** [comment]
@JosVanderArend @rrutte @roelgrif @mcginkel.
We hebben op dit moment in flow 1 nog een ADD organization staan als kopje is dit nodig en doen we dat op basis van een GET bij Deelnemerregistratie? In dat geval zou er nog een extra endpoint bij komen GET /ooapi/organizations/{organizationId}
of is het idee juist om dit op te lossen door een aanpassing in de expand:
GET /ooapi/associations/{associationId}?expand=offering.program,offering.organization

**Comment by roelgrif** [comment]
Dat laatste moet in ieder geval ook kunnen. Dat is ook hoe wij het gemaakt hebben voor pilot 2. Voor mij is dat aparte endpoint niet nodig (noch wenselijk) maar dat kan vanuit TPS anders gezien worden uiteraard.

**Comment by rrutte** [comment]
Vanuit TPS is de noodzaak van de GET /ooapi/organizations/organizationId afhankelijk van de wijze van expand op offering.organiztion. Als daar ook de parent organization expand wordt van de organization die gekoppeld is aan de offering dan hebben we toch graag een GET organization om op basis van de parentOrganization uuid de gegevens van de parent op te halen.

**Comment by hamrt** [comment]
toegevoegd in comit  https://github.com/NetwerkExamineringDigitalisering/NED-OOAPI/commit/cb1f37cbbc0f491c28474660236186408f7abe32 en fixed

**Comment by jonasdegraaff** [comment]
Wij hebben de GET /ooapi/organizations/{organizationId} al eerder geimplementeerd omdat deze ook voor andere koppelingen wordt gebruikt en ook in de algemene OOAPI spec staat gespecificeerd. Wat ons betreft mag hij dus worden toegevoegd.

**Comment by roelgrif** [comment]
Omdat bij ons de parent organization in de expand van offering.organiztion altijd leeg is, is de GET voor ons dus niet van toepassing begrijp ik. Correct @rrutte ?
