### ISSUE TITLE
Kopieerfoutjes in YAML van MembershipItem

### ISSUE THREAD

**Issue by JosVanderArend** [NetwerkExamineringDigitalisering/NED-OOAPI#116]
In de YAML van MembershipItem (zie https://github.com/NetwerkExamineringDigitalisering/NED-OOAPI/blob/v0.9.3/specification/v5/schemas/MembershipItem.yaml) staat bij required attribute "startDate", maar dit attribuut bestaat niet, wel startDateTime. 

De bijbehorende beschrijving "A newsitem contains the message and metadata of that message" klopt ook niet!

In de YAML van GroupMembeship (zie https://github.com/NetwerkExamineringDigitalisering/NED-OOAPI/blob/v0.9.3/specification/v5/paths/GroupMemberships.yaml) staat als beschrijving bij GET /groups/{groupId}/members: "Get an ordered list of all persons that are member of a given group, ordered by personId".
Dat laatste klopt zeker niet: je krijgt een lijst van MembershipItems.

**Comment by hamrt** [comment]
en gefixed sluiten als OK

**Comment by JosVanderArend** [comment]
OK
