### ISSUE TITLE
Scopes voor berichtstromen?

### ISSUE THREAD

**Issue by rrutte** [NetwerkExamineringDigitalisering/NED-OOAPI#117]
We hebben het in het begin gehad over het gebruik van scopes tbv OAuth2.0.

In onze situatie zouden we bijvoorbeeld scopes per flow willen kunnen toekennen aan een client zodat we ook zeker weten dat alleen de juiste soort berichten worden uitgewisseld en als bijkomend voordeel dat we opties wat voor soort association een call is bijvoorbeeld beperken.

**Comment by mcginkel** [comment]
we moeten scopes hebben per setje van flows: 2-3-4 heeft al test-admin-flow. Ik zou een andere scope verwachten voor de combi 1-5 en apart voor 0 en voor 6

**Comment by hamrt** [comment]
@hamrt uitwerken van de scopes in de yaml file. nummering van de flows mee nemen in de naming convention

**Comment by hamrt** [comment]
- oAuthFlows:  
      - nl-test-admin-flow-1-5
      - nl-test-admin-flow-2-3-4
      - nl-test-admin-flow-0
      - nl-test-admin-flow-6
   voor 0.9.3 nog doorvoeren

**Comment by hamrt** [comment]
opgenomen in documentatie
