### ISSUE TITLE
Required indicatie op attributen in consumer objecten (in yaml file)

### ISSUE THREAD

**Issue by rrutte** [NetwerkExamineringDigitalisering/NED-OOAPI#118]
Op dit moment staan in de yaml bij attributen binnen nl-test-admin geen required indicatoren. Dit levert nu al onduidelijkheden op die je niet wilt hebben op het moment dat de standaard gereleased wordt.

Extra complicatie: Hoe gaan we om met attributen die alleen required zijn in een bepaalde flow?

**Comment by hamrt** [comment]
Roel, Huib-Jan, Rene, Ronald en Jos als trekkers

**Comment by hamrt** [comment]
@mcginkel kun jij als owner van de repo @hjwielemaker nog toevoegen als member van de groep?

**Comment by hjwielemaker** [comment]
In aanvulling op de 4 oplossingsrichtingen die opgenomen waren in de sheets is er nog een methode die hiervoor in aanmerking komt. Voor het kunnen onderscheiden van het verplicht zijn van velden tussen de verschillende flows kan gebruik gemaakt worden van een discriminator (welke voorkomt in de OpenAPI specification). Binnen de consumer kan de discriminator gebruikt worden om verschil te maken tussen de flows, waarbij daarbinnen dan per flow aangegeven kan worden welke velden er van toepassing zijn en welke verplicht zijn.

Binnen bijvoorbeeld GET person heb je de consumer nl-test-admin, met daarbinnen de flow als discriminator
-	propterty
o	propertyName: flow
o	mapping
o	soort oneOf / anyOf
	flow1
	flow2
	flow3
	flow4
	flow5
-	discriminator: flow

Vervolgens geef je per flow de velden aan en of deze verplicht zijn

-	flow1
o	name
	string
	optional
-	flow2
o	name
	string
	required

Dit principe kan gebruikt worden voor het onderscheiden van de flows, maar ook voor de verschillende allianties binnen eduXchange

**Comment by hamrt** [comment]
We parkeren dit op dit moment mogelijk punt om mee te nemen richting de bredere OOAPI werkgroep @hamrt
