### ISSUE TITLE
Standaard mtls een issue?

### ISSUE THREAD

**Issue by rrutte** [NetwerkExamineringDigitalisering/NED-OOAPI#120]
Als Xebic willen we af van whitelisting van onze integratieservices en overgaan op mtls. OOAPI als standaard lijkt open te staan voor additionele authenticatiemethodes.

Is het een issue als wij alle uitgaande berichten voorzien van signing?

**Comment by boerrookhuiszen** [comment]
Ik sluit me bij @roelgrif aan, ik verwacht geen problemen maar het is slim dit gewoon even uit te testen.

**Comment by mcginkel** [comment]
update Ronald: educonnect/edustandaard is dit opnieuw aan het bekijken. ooAPI commissie houd vingen aan de pols.
