### ISSUE TITLE
Result waarden in OKE-koppeling 3

### ISSUE THREAD

**Issue by JosVanderArend** [NetwerkExamineringDigitalisering/NED-OOAPI#122]
Bij het testen van de OKE-koppeling 3 tussen Eduarte en TOA blijkt dat het veld score in het object result niet kan omgaan met de verschillende scoreweergaven die TOA kan meegeven aan toets- en examenresultaten: referentieniveau, cijfer, aantal goed, percentage, tekstuele uitslag. 

Welke mogelijkheden zien jullie vanuit de werkgroep Techniek om hier binnen de OOAPI-standaard mee om te gaan?

Met vriendelijke groet,
Johan Verhaar

**Comment by rrutte** [comment]
Ik denk dat je aan score, rawScore en comment in principe genoeg hebt in flow 3

Voor score (waar een ooapi enumeratie aan hangt) ben je minder flexibel, maar misschien zou je daarvoor een resultValueType "text" oid aan toe kunnen voegen waar je van alles in kan voeren.

Vraag is wat we doen met de resultValueType in flow 5. Deze kan bijvoorbeeld een O/V/G verwachten waardoor je ergens moet gaan vertalen wat via flow 3 is ontvangen en wat in flow 5 weer moet worden aangeleverd. Als dat overigens al een vereiste is.

**Comment by mcginkel** [comment]
principe blijft dat de toets applicatie de score bepaalt en de rest van de waarden informatief zijn ?

**Comment by JosVanderArend** [comment]
Johan stuurde mij het volgende voorbeeld:
![afbeelding](https://github.com/NetwerkExamineringDigitalisering/NED-OOAPI/assets/36879018/a0173feb-794a-4f8d-96a5-664779141948)

Daar heb ik de volgende oplossing op gestuurd:
![afbeelding](https://github.com/NetwerkExamineringDigitalisering/NED-OOAPI/assets/36879018/8615e0cc-961a-4de2-b9b4-924f1a07d6de)

**Comment by hamrt** [comment]
Voorlopig kan op deze manier gewerkt worden. 

Dit punt kan verder uitgediept worden voor een volgende versie. Vergt wel input vanuit de werkgroep OKE (actiepunt richting Ruud) Mogelijk een oploopje organiseren tussen instellingen en toetsleveranciers? later pas op de roadmap iig.
