### ISSUE TITLE
Toevoegen van informatie over endpoints en versies in het service endpoint

### ISSUE THREAD

**Issue by hamrt** [NetwerkExamineringDigitalisering/NED-OOAPI#123]
Het Service endpoint wat nu op "/" gedefinieerd staat bevat een beperkte set:

"contactEmail": "api-admin@mbodigitaal.nl",
"specification": "https://rawgit.com/open-education-api/specification/v5/docs.html",
"documentation": "https://open-education-api.github.io/specification/v5/docs.html",
"supportedEndpoints": [
{
 method: "GET",
 endpoint: "associations"
},
{
 method: "PUT",
 endpoint: "associations"
},
]
"supportedConsumers": [
{
"consumerKey": "nl-test-admin",
"version": "0.9.3"
},
{
"consumerKey": "eduxchange",
"version": "v1"
},
],
"consumers": [
{
"consumerKey": "x-test-consumer",
"additional": "custom",
"attributes": "here"
}
],
"ext": { }

**Comment by hamrt** [comment]
toe te voegen na 0.9.3 (e.g. 0.9.4)

**Comment by boerrookhuiszen** [comment]
Volgens mij kunnen we `specification` (URL of the API specification (YAML or JSON, compliant with Open API Specification v3) goed gebruiken om aan te geven welke endpoints door een applicatie ondersteund worden. 

Hiermee kun je echter volgens mij niet doorgeven welke versie(s) je ondersteund, en al helemaal niet als dat per endpoint kan verschillen. 

Ook zeg je enkel iets over de endpoints die je als applicatie aanbiedt, niet over de versies die je extern aanroept. Moet dat ook toegevoegd worden?

**Comment by hamrt** [comment]
hoe documenteren we het gebruik van een subset van een bredere standaard op een uniforme wijze? Zijn hier voorbeelden van

**Comment by hamrt** [comment]
bare minimum is iig aangeven welke OOAPI versie en welke Versie van de consumer geldt

**Comment by hamrt** [comment]
Volgende itteratie: op "/" gedefinieerd staat bevat een beperkte set:

"contactEmail": "[api-admin@mbodigitaal.nl](mailto:api-admin@mbodigitaal.nl)",
"specification": "https://mbo-instelling.nl/specification/v5/spec.yaml",
"documentation": "https://open-education-api.github.io/specification/v5/docs.html",
"supportedVersions": [
"v4", "v5"
"supportedConsumers": [
{
"consumerKey": "nl-test-admin",
"version": "0.9.3"
},
{
"consumerKey": "nl-test-admin",
"version": "0.9.4"
},

{
"consumerKey": "eduxchange",
"version": "v1"
},
],
"consumers": [
{
"consumerKey": "x-test-consumer",
"additional": "custom",
"attributes": "here"
}
],
"ext": { }

**Comment by mcginkel** [comment]
"supportedVersions": [
"v0.93-OKE", "v1.0-OKE"
]

**Comment by hamrt** [comment]
verder uitwerken op basis van 2e voorstel

**Comment by hamrt** [comment]
dit is hem geworden:
{
"contactEmail": "admin@universiteitvanharderwijk.nl",
"specification": "https://rawgit.com/open-education-api/specification/v3/docs.html#tag/course-offerings/paths/~1course-offerings/get",
"documentation": "https://open-education-api.github.io/specification/v4/docs.html",
"supportedVersions": [
"v5"
],
"supportedConsumers": [
{
"consumerKey": "nl-test-admin",
"version": "0.9.3"
}
],
"consumers": [
{
"consumerKey": "x-test-consumer",
"additional": "custom",
"attributes": "here"
}
],
"ext": { }
}

**Comment by hamrt** [comment]
Nog toevoegen informatie over wel of niet geauthenticeerde toegang.

**Comment by JosVanderArend** [comment]
@hamrt , ik zie het service metadata endpoint op branch 0.9.4: 
![afbeelding](https://github.com/NetwerkExamineringDigitalisering/NED-OOAPI/assets/36879018/a2493204-bdef-41f4-86ed-5bfa71f3e5df)

Maar binnen object ConsumerVersion van supportedConsumers:
- Is alleen 'consumerKey' verplicht. Is 'version' niet verplicht? Zo nee, wat betekent dit dan (alle versies of alleen de actuele versie ondersteund)?
- Wat betekent het derde attribuut 'property name'? Wat levert dit extra gegeven op als dit geen afgesproken naam heeft? Voor extra info is een attribuut 'comment' handiger!

**Comment by hamrt** [comment]
Ha Jos terechte opmerking ik neem de versie ook mee voor de consumerKey. De extra properties kunnen idd vervallen. Dat maakt het compacter. Ik pas het aan.
