### ISSUE TITLE
GET /groups/{groupId} toevoegen aan flow 1

### ISSUE THREAD

**Issue by JosVanderArend** [NetwerkExamineringDigitalisering/NED-OOAPI#124]
Ik zie in de OAS-definities ook het endpoint GET /groups/{groupId} staan, https://netwerkexamineringdigitalisering.github.io/NED-OOAPI-DEV/specification/v5/docs.html#tag/groups/operation/listGroupById.
Alleen dit endpoint staat niet genoemd/gedefinieerd in het specificatiedocument en ook niet in flow 1. 

Ik denk dat het een consistente en bruikbare operatie is. Behouden we deze GET /groups/{groupId} en zal ik het ook aan het specificatiedocument toevoegen?
Zo ja, dan moet het ook aan flow 1 worden toegevoegd!

**Comment by roelgrif** [comment]
Lijkt mij prima, om b.v. de naam van de groep of de status te achterhalen zonder per se de hele groepenlijst te moeten langsgaan.

**Comment by hamrt** [comment]
Opgenomen in de nieuwe documentatie. voor 0.9.3 @hamrt check of ook in flow1.md aanwezig
