### ISSUE TITLE
discriminator voor consumer in spec voor code generatie

### ISSUE THREAD

**Issue by mcginkel** [NetwerkExamineringDigitalisering/NED-OOAPI#125]
voor de codegeneratie is het fijn als we in de spec een discriminator op het veld "consumerKey". Hierdoor kan de code generator al code maken om de berichten te decoderen.

(Dit is op OOAPI niveau, maar we kunnen dit voor de OKE spec vast implementeren)

https://redocly.com/docs/resources/discriminator/

**Comment by hamrt** [comment]
hoe om te gaan met een array van consumers?

**Comment by hamrt** [comment]
voor discussie binnen OOAPI werkgroep @hamrt
