### ISSUE TITLE
versie 0.94 releasen als versie 1.0

### ISSUE THREAD

**Issue by mcginkel** [NetwerkExamineringDigitalisering/NED-OOAPI#126]
Bij onze klanten is er soms wat "verwarring" dat we een OKE koppeling opleveren met een minor versie (0.93) terwijl we aangeven dat dit in productie gebruikt kan worden. Als we de versie 0.94 uitleveren als (mijlpaal) versie 1.0 kunnen we daarna incrementeel verbeteringen toevoegen.

**Comment by JosVanderArend** [comment]
Streven is om in het overleg van de Kerngroep Techniek op 20 augustus versie 0.9.4 van de specificaties (Github, specificatiedocument en YAML) goed te keuren en daarna asap (binnen een dag) deze versie als 1.0 te publiceren!
@hamrt, zou dat gaan lukken?

**Comment by JosVanderArend** [comment]
gedaan
