### ISSUE TITLE
Het attribuut assignedNeeds in object Person is voor flow 1 en niet voor flow 2

### ISSUE THREAD

**Issue by JosVanderArend** [NetwerkExamineringDigitalisering/NED-OOAPI#128]
Het attribuut assignedNeeds wordt in flow 2 op verschillende plaatsen (class diagram en JSON-examples) beschreven in consumers van object Person. Maar assignedNeeds is voor flow 1 en niet voor flow 2; in flow 2 hebben we personalNeeds in consumers van object ComponentOfferingAssociation (Deelname) daarvoor.

In het specificatiedocument staat het wel als alleen voor flow 1 gespecificeerd: 
- Dit attribuut verschijnt niet in object Person in fow 2 (zie Figuur 3.2.8 in Paragraaf 3.2.3 Koppelvlak bij Toetsafname), 
- In beschrijving van attribuut personalNeeds staat: "Lijst van toegekende hulpmiddelen (inclusief extra tijd) voor de student gebaseerd op diens behoefte. Deze toegekende hulpmiddelen worden later vertaald naar persoonlijke hulpmiddelen voor een specifieke deelname."  (zie Tabel Tabel 4.10.A in Paragraaf 4.10 Person), en
- In beschrijving van attribuut personalNeeds staat als aanvullende eis: "alleen gebruikt voor persoonsgegevens van een student in flow 1." (zie Tabel Tabel 4.10.A in Paragraaf 4.10 Person).

Dit levert verwarring op en moet worden gecorrigeerd in flow 2 (volgens mij).

**Comment by hamrt** [comment]
Aangepast (ook in 0.9.3)
