### ISSUE TITLE
Flow 3 en 4: Describe document types

### ISSUE THREAD

**Issue by JosVanderArend** [NetwerkExamineringDigitalisering/NED-OOAPI#13]
Make the complete list of document types for offering (zitting, whole group) and association (individual student)

**Comment by rrutte** [comment]
Documenttypes:

tbv flow 4
- attendanceRegister (Presentielijst)
- officialReport (Procesverbaal)

tbv flow 3
- assessmentForm (Beoordelingsformulier)
- assessmentAnnex (Beoordelingsbijlage)
- documentsHandedIn (ingeleverde documenten)
- plagiarismScan (Plagiaatscan bij ingeleverd document)

**Comment by hamrt** [comment]
document types are now part of an enumeration documentTypes.yaml this element can later be used for the documents endpoint.
