### ISSUE TITLE
Toevoegen van documentatie voor het gebruik van assesor rol in flow 2  

### ISSUE THREAD

**Issue by hamrt** [NetwerkExamineringDigitalisering/NED-OOAPI#130]
Om externe assessors toegang te verlenen tot beoordelingsformulieren voor een (praktijk)toets is het nodig om het gebruik van flow 2 als assesor en het gewenste gedrag van de tools te laten zien.

**Comment by hamrt** [comment]
Uitleggen hoe dit werkt voor alle rollen. (niet alleen externe medewerkers)

**Comment by JosVanderArend** [comment]
@hamrt: Het endpoint GET /associations/{associationId}/url is gedefinieerd in OAS, maar ik kan in flow 2 helemaal niets over dit endpoint vinden. Dat moet er nog bij!
