### ISSUE TITLE
Onvoldoende informatie in flow 1

### ISSUE THREAD

**Issue by JosVanderArend** [NetwerkExamineringDigitalisering/NED-OOAPI#131]
In de afgelopen maanden zijn door Topicus (Eduarte) en Bureau ICE (TOA) de nieuwe OKE-koppelingen 0, 2, 3 en 4 ontwikkeld en in een eerste gebruikerstest bij Albeda College in Rotterdam getest, dit in aanwezigheid van de OKE-projectgroep en ROC van Amsterdam. Het was een goede testsessie in een positieve sfeer en met goede testresultaten. Er is een nieuwe testsessie in april gepland om de oplossingen van de belangrijkste testbevindingen te hertesten.

Uit analyse van OKE-koppeling 1 blijkt dat er volgens de OOAPI-standaard voor het inplannen van examens onvoldoende gegevens worden verstuurd vanuit het administratiesysteem naar het planningsysteem en het toetssysteem. Concreet gaat het hierbij om de gegevens van afdelingen, groepen, hulpmiddelen en medewerkers. Voordat er nieuwe of aanvullende koppelingen door leveranciers en mbo-instellingen worden gebouwd, is de concrete vraag: hoe wordt hier binnen het OKE-project mee omgegaan? Graag zouden we dit bespreken in de OKE-werkgroep Techniek.

Ik zie uit naar jullie reactie,
Met vriendelijke groet,
Johan Verhaar

**Comment by roelgrif** [comment]
Wordt met 'koppeling 1' flow 1 bedoeld? zo ja, dan kan ik de toevoeging 'en het toetssysteem' niet plaatsen. Groepen en afdelingen zijn volgens mij overigens wel voorzien in flow 1 (groups/organizations). Hulpmiddelen en medewerkes wellicht in flow 2?

**Comment by rrutte** [comment]
Alle in de mail van Johan benoemde elementen kunnen conform standaard OKE/OOAPI aangeleverd worden aan TPS in flow 1

Afdelingen: in kader van programOfferingAssociation
Groepen: zowel group als groupMembership wordt ondersteund als aparte endpoints
Hulpmiddelen/voorzieningen: De personalNeeds/assignedNeeds op person
Medewerkers: In principe kan je een person als employee aanleveren.

Eigenlijk bestaat de vraag uit een aantal sub onderdelen:

1. Welke elementen zitten al wel in de standaard OKE scope
2. Welke elementen zitten nog niet in de standaard OKE scope maar wel in OOAPI V5
3. Welke elementen zitten wel in de standaard OKE scope maar worden niet geleverd door een specifiek SIS
4. Welke elementen/attributen verwacht TOA die niet in bovengenoemde  punten voorkomen

En daaruit -> als er na deze exercitie missende elementen/attributen vastgesteld zijn, passen die in een nieuwe versie van OKE?

**Comment by JosVanderArend** [comment]
In het overleg van zojuist (dinsdag 16 april) zijn de vragen van TOA (Johan Verhaar) besproken. Samenvattend zijn de volgende punten besproken/afgesproken:
- TOA heeft de koppeling 2+3+4 als TA geïmplementeerd; TOA onderzoekt of het in bepaalde ketens de rol van TPL en TA kan vervullen, dus koppelingen 1+5.
- OKE biedt de mogelijkheid om medewerkers te koppelen aan een Planbare toets of Zitting via Toetsinschrijving respectievelijk Toetsdeelname. TOA heeft behoefte aan medewerkers in andere rollen dan de huidige beschikbare rollen: afnameleider, surveillant en beoordelaar. Het gaat hierbij om de rollen examencommissielid (vaststellen van examens) en instellingsbeheerder (organisatiebrede activiteiten). Beide rollen zijn toets/zittingsoverstijgend en dus niet aan 1 planbare toets/zitting gekoppeld.
- TOA heeft behoefte aan informatie over de afdeling/groep van de student voor het maken van afdelings- en groepsoverzichten van de resultaten. In het geval TOA ook TPL is, is deze informatie in flow 1 beschikbaar. Het nut en de noodzaak van het maken van groepsoverzichten lijkt steeds meer af te nemen doordat groepen een steeds meer ondergeschikte rol gaan vervullen.
Om deze informatie in de situatie van TOA als TA te behouden heeft TOA een werkende koppeling maar de voorkeur gaat ernaar uit deze koppeling te kunnen uitzetten. Opties binnen OKE zouden zijn: uitwerking van flow 6 Analysegegevens om deze contextgegevens op te vragen of gegevens volgens flow 1 opvragen (let op, alleen als TOA TPL+TA is)
- TOA heeft behoefte aan informatie over de afdeling van de student voor het kunnen factureren aan de juiste afdeling binnen de mbo-instelling. Het attribuut organization binnen object ComponentOffering lijkt in eerste instantie bruikbaar. Dan moet wel de informatievoorziening gegarandeerd worden (verplicht gevuld). De verplichting is wel een extra eis, en voor opleidingsoverstijgende examens (bijv. rekenexamens) lijkt dit juist weer niet zo handig.

**Comment by hamrt** [comment]
We sluiten deze voor nu flow 6 biedt additionele info #28
