### ISSUE TITLE
Flow 3 documentType

### ISSUE THREAD

**Issue by rrutte** [NetwerkExamineringDigitalisering/NED-OOAPI#133]
In de documentatie hebben we geen eisen gesteld aan het documentType in flow 3 (en flow 4). Kunnen we dat wel gaan doen? Op dit moment levert bijvoorbeeld Remindo een documentType "other" aan. Dit beschouwen wij als een additioneel documenttype waar wij verder geen waarde aan hechten en dus ook niet opslaan of doorgeven

**Comment by JosVanderArend** [comment]
Type other mag alleen als het geen van de voorbedachte typering is

**Comment by hamrt** [comment]
Staat al in de documentatie. zie ook #136
