### ISSUE TITLE
Moeten documenten verplicht uitgewisseld worden ?

### ISSUE THREAD

**Issue by mcginkel** [NetwerkExamineringDigitalisering/NED-OOAPI#136]
In een pilot worden ook de examens en vragen teruggestuurd in koppeling 3. Niet iedereen denk dat dit de bedoeling was. graag bespreken.

**Comment by mcginkel** [comment]
In het protocol is er ruimte, applicaties mogen daar onderling bedenken wat ze willen delen. hangt ook sterk af van soort examen. als er bv praktijkexamens over de koppeling aan kan er best meer nodig zijn.

**Comment by boerrookhuiszen** [comment]
Volgens mij gaat dit vraagstuk over de inhoud van de teruggestuurde document(en). 

Hebben we duidelijk omschrijven wat het _doel_ is van het uitwisselen van documenten? Moeten we dat wellicht duidelijker per type document aangeven? Wellicht dat daaruit volgt welke informatie wel en niet in een specifiek document moet worden opgenomen en aan wie dit getoond moet worden.

Uit spec:
Flow 3: `PATCH /associations/{associationId}`
```identifies the kind of document; supported values: "assessmentForm" (beoordelingformulier), "assessmentFormWithAnswers" (answers with assessment notes), "assessmentModel" (beoordelingsmodel/-voorschrift), "other" (any document not suitable for the other values).```

Flow 4: `PATCH /offerings/{offeringId}`
```"sessionReport" "attendanceReport" "assessmentModel" "other"```

Ter illustratie, Remindo stuurt momenteel de volgende documenten:

- In flow 3 deelnemerresultaat (documentType: other): Het volledige resultaat (naam in Remindo: Export van detail van het resultaat, inclusief alle beschikbare informatie: gegeven antwoord, juiste antwoord, cesuur, cijferberekening etc.).
- In flow 4 zittingsverslag (documentType: sessionReport): Alle details van het toetsmoment (naam in Remindo: Verantwoordwoordingsrapportage toetsmoment)

**Comment by hamrt** [comment]
Nee, ze hoeven niet verplicht uitgewisseld worden.

**Comment by mcginkel** [comment]
de afname systeem mogen zelf kiezen welke data ze sturen naar de planning, de planning mag kiezen welke documenten ze aanbieden aan de SIS.

Dit zijn keuzes die de applicatie leveranciers kunnen aanbieden aan de scholen. Ook de inhoud van de documenten is aan de afname systemen. 

voorbeeld : Als er geen examen vragen mogen lekken is het niet handig om deze in de beoordelings documenten te tonen, het afname systeem moet dat regelen. Bij een ander soort examen, bv praktijk examens is het juist wel fijn dat de vragen of beoordeling wel in het document ziet. Hierdoor kan de OKE er niets voor verplichten, maar alleen de ruimte geven om het door te geven.
