### ISSUE TITLE
Verschillen bij afname applicatie implementatie: hoe gaan we er me om?

### ISSUE THREAD

**Issue by mcginkel** [NetwerkExamineringDigitalisering/NED-OOAPI#138]
Bij het testen met remindo en TOA zien we dat leveranciers anders omgaan met de data die we ze sturen (bv start/eind datums tijd.)

< Deze lijst word straks hier toegevoegd >

Voor scholen is dat lastig te begrijpen. Hoe gaan we (en de scholen) zicht houden  of een applicatie de concepten van de OKE wel of niet ondersteund (of nog niet) en hoe communiceren we dat naar scholen ?
Rapport per applicatie met afwijkeingen/ niet geimplementeerde zaken ?

**Comment by mcginkel** [comment]
Als ik de detail lijst heb zet ik die erbij en hebben we wat concreets om over te praten.. Even wachten tot die tijd?

**Comment by hamrt** [comment]
Werner neemt hier actie op (zie [https://github.com/NetwerkExamineringDigitalisering/NED-OOAPI/blob/main/doc/flow2.md#remarks](https://github.com/NetwerkExamineringDigitalisering/NED-OOAPI/issues/url) en [Opties bij het toetsmoment in praktijk.pdf](https://github.com/user-attachments/files/15531934/Opties.bij.het.toetsmoment.in.praktijk.pdf)

**Comment by hamrt** [comment]
Dit is een punt voor de werkgroep

**Comment by mcginkel** [comment]
gaat naar de werkgroep. Zij moeten aangeven waar je kunt zien welke combinatie een app ondersteunt.
