### ISSUE TITLE
Uitbreiden Flow 0 met meer info

### ISSUE THREAD

**Issue by JosVanderArend** [NetwerkExamineringDigitalisering/NED-OOAPI#139]
Uit pilot 1 (via Freek Pino) is het volgende vraagstuk naar voren gekomen: Kan Flow 0 worden uitgebreid met meer info voor betere matching naar bijv crebo en cohort?

Deze informatie lijkt bij een aantal examenleveranciers weldegelijk bekend. In eerste instantie lijkt de oplossing te kunnen worden gevonden in de otherCodes van de Toets (object Component).

**Comment by rrutte** [comment]
Op zich wordt dit al ondersteund met de otherCodes sectie. Remindo vult dit al met eigen codeTypes, maar ik zou voorstellen dat we een OKE set aan codeTypes vastleggen om geautomatiseerde verwerking te vereenvoudigen.

**Comment by JosVanderArend** [comment]
Ik vraag me oprecht af of we hiervoor otherCodes moeten gebruiken. In de omschrijving van dit attribuut staat "An array of additional human readable codes/identifiers for the entity being described.". En ik vind de betreffende kwalificatiecodes (crebo/cohort) toch een andere entiteit dan de toets/component zelf.

**Comment by JosVanderArend** [comment]
Afgelopen woensdag (pilot 1 evaluatie) kwam ik erachter dat het bij pilot 1 (Eduarte & Remindo/CEM) al is geïmplementeerd via otherCodes!

**Comment by rrutte** [comment]
@JosVanderArend Dit zie ook terugkomen als we via flow 0 toetsen ophalen bij Remindo. Dit gebeurt momenteel echter met custom "x-" codeTypes. Ik snap dat dat voor de pilot zo geïmplementeerd is, maar zou graag voorstellen om een aantal standaard codeTypes te definieren zodat we niet voor elk afnamesysteem maatwerk hoeven te bouwen tav het herkennen van codeTypes. Daarnaast is de opmerking van Jos terecht dat het maar de vraag is of codeTypes wel het juiste vehicle is voor deze metadata, vooral ook omdat het hierbij om lijsten van informatie kan  gaan.

**Comment by boerrookhuiszen** [comment]
@JosVanderArend Volgens mij wordt nu in de pilot geen gebruik gemaakt van de extra gegevens die teruggegeven worden via othercodes ("x-RemindoStudyName" bijvoorbeeld), maar is het bijvoorbeeld opgenomen in de titel waardoor het getoond werd. Daardoor "werkt" het nu wellicht, maar is dit geen toekomstbestendige oplossing. Willen we specifieke "otherCodes" definiëren om deze waarden door te kunnen geven?

**Comment by JosVanderArend** [comment]
We kiezen ervoor om deze informatie toe te voegen aan description

**Comment by hamrt** [comment]
opgenomen in de documentatie
