### ISSUE TITLE
Documentatiepagina's op Github bijwerken

### ISSUE THREAD

**Issue by JosVanderArend** [NetwerkExamineringDigitalisering/NED-OOAPI#140]
Een aantal documentatiepagina's binnen deze Github-repository zijn verouderd of nooit uitgewerkt. Ik denk hierbij voornamelijk aan deze paragraaf en onderdelen: https://github.com/NetwerkExamineringDigitalisering/NED-OOAPI?tab=readme-ov-file#structure-of-this-repository

Deze info moet worden bijgewerkt of weggehaald...

**Comment by hamrt** [comment]
vooral opruimen en weghalen wat niet meer klopt

**Comment by JosVanderArend** [comment]
Gedaan
