### ISSUE TITLE
Verplichte namen bij (externe) medewerker

### ISSUE THREAD

**Issue by JosVanderArend** [NetwerkExamineringDigitalisering/NED-OOAPI#141]
Binnen het object Person zijn er verschillende verplichte attributen die over namen gaan:
- givenName (voornaam/voornamen)
- displayName (weergavenaam)
- preferredName (roepnaam)
- idCheckName (naam zoals vermeld op legitimatiebewijs)

Ik vraag me af of deze attributen ook voor de medewerker verplicht moeten zijn, ofwel kunnen deze gegevens allemaal door het SIS worden aangeleverd voor een medewerker?
En misschien nog relevanter: in TPL kunnen externe medewerkers worden ingevoerd en worden toegevoegd aan een zitting (middels Association/Deelname) richting TA. Kunnen deze gegevens allemaal door het TPL worden aangeleverd voor een externe medewerker?

**Comment by rrutte** [comment]
Als we het hebben over flow 2 dan zou ik voor medewerkers alleen de volgende attributen verplicht willen stellen:

1. preferredName
2. SurName
3. displayName

en optioneel surnamePrefix en initials.

Als ik bij de beschikbare codeTypes kijk (voor primaryCode) kom niet "employeeNumber" tegen oid. Is dit wenselijk of gaan we hier voor medewerkers accountId of UserName gebruiken in de primaryCode?

**Comment by JosVanderArend** [comment]
Voor medewerker wordt attribuut givenName en idCheckName dan ook optioneel voor medewerker, maar verplicht voor student. 
Attribuut initials wordt helemaal niet gebruikt in OKE.

**Comment by JosVanderArend** [comment]
Kleine complicatie: attribuut givenName is verplicht in object Person van OOAPI, zie https://openonderwijsapi.nl/specification/v5/docs.html#tag/person_model.
Attribuut givenName is dus ook voor medewerker verplicht!

**Comment by roelgrif** [comment]
specificatiedocument is bijgewerkt, idCheckname niet verplicht voor medewerker
givenName wel.

**Comment by hamrt** [comment]
bijgewerkt in spec en document
