### ISSUE TITLE
Specificatie associations in verschillende flows nog steeds multi interpretabel

### ISSUE THREAD

**Issue by rrutte** [NetwerkExamineringDigitalisering/NED-OOAPI#144]
Bij testen flow 5 kwamen we erachter dat Osiris personId en offeringId verwacht op de association terwijl de verschillende voorbeelden die niet aanleveren.

Het gaat er hierbij niet om wie de specs op de juiste manier interpreteert, maar hoe we dit voorkomen. Deze situatie levert bijvoorbeeld onduidelijkheid en dus vertraging op omdat één van de partijen werk moet gaan verzetten dat niet was ingeschat en dus tot vertraging kan leiden.

**Comment by JosVanderArend** [comment]
Volgens het specificatiedocument (paragraaf 4.3) zijn binnen het object ComponentOfferingAssociation de attributen person en offering (personId/offeringId of object) verplicht.

Deze attributen ontbreken in de figuren 3.5.4 en 3.5.5 omdat dit de PATCH gegevensmodellen in flow 5 zijn. Voor een PUT in flow 5 (figuur 3.5.6) is deze wel aanwezig.

**Comment by rrutte** [comment]
Gesloten en wordt opgepakt
