### ISSUE TITLE
verschillende interpretatie omtrent welke association ID's te gebruiken bij meerdere pogingen

### ISSUE THREAD

**Issue by roelgrif** [NetwerkExamineringDigitalisering/NED-OOAPI#148]
We merken in pilot 2 dat door de verschillende partijen aan het gebruik van associationId en orgAssociationId een verschillende invulling is gegeven.
Ons (PeopleSoft) uitgangspunt was:
SIS levert in flow 1 association id X met attempt 1
TPS levert in flow 5 resultaat op association id X en attempt 1 via PATCH (of PUT)
TPS levert in flow 5 eventueel een extra resultaat op association id Y en attempt 2 via PUT met orgAssociationId X

Nu zien we vanuit TPS resultaten binnenkomen met PUT van association id Y en attempt 1 en een extra resultaat met PUT van association id Z en attempt 2 (beide met orgAssociationId X).
De combinatie association id Y en attempt 1 'past' bij ons niet, omdat we daar al een bestaand association id X bij geregistreerd hebben, stel dat we het mogelijk zouden maken dit als een nieuwe resource opslaan aan onze kant, dan hebben we tweemaal dezelfde poging staan waarvan 1 met en 1 zonder cijfer. Dit is voor ons pakket verwarrend en ongewenst, ook in het koppelvlak kan het verwarring geven als je rekening houdt met toekomstig gebruik van GET services. Welk van de 2 association ID's gaat bevraagd worden met zo'n GET?

Het lijkt me goed om hier eenduidigheid in af te spreken. Wellicht moet e.e.a. nog scherper geformuleerd worden in het specificaties document maar ik krijg de indruk in 3.5.2. dat een nieuw aan te leveren associationId vanuit het TPS alleen bedoeld is indien daar een nieuwe poging 'aangemaakt' wordt en niet als die al door het SIS aangemaakt is.

**Comment by rrutte** [comment]
Interpretatie van Xebic (TPS) is als volgt.

SIS stuurt als componentOffering/Associations  toetsinschrijvingen met opgegeven pogingen constraints.

TPS stuurt op alle toetsinschrijving resultaten van toetspogingen (met een uniek ID) binnen het ID van de toetsinschrijving met elk resultaat terug naar SIS

**Comment by hamrt** [comment]
@JosVanderArend mogelijk 3.5.2 verder aanvullen met een voorbeeld @rrutte kan mogelijk wel een voorbeeld aanleveren. Met name verduidelijken hoe met pogingen het beste omgegaan kan worden met verschillende vormen van het afhandelen van extra pogingen door het TPS.

**Comment by JosVanderArend** [comment]
We hebben het als volgt afgesproken (zoals ook afgesproken met Roel):
Het SIS geeft soms en soms de vrijheid aan TPS om meerdere pogingen in te plannen en af te laten nemen. Dit wordt middels het attribuut attemptLeft overgedragen:
- attemptLeft = 0: Er is geen extra poging toegestaan (TPS mag dus 1 keer inplannen)
- attemptLeft = 1, 2, 3, etc.: Er zijn extra pogingen toegestaan, zoals waarde aangeeft (TPS mag dus meerdere keren inplannen)
- attemptLeft = null (of 999): Er zijn zoveel pogingen toegestaan zoals nodig (TPS mag dus 'onbeperkt' inplannen).
Voorbeeld: Het SIS geeft TPS de mogelijkheid 1 extra poging in te plannen (attemptLeft=1) en na de extra poging bepaalt het SIS via een nieuwe toetsinschrijving of een 3e of zelfs 4e poging is toegestaan.
Opmerking: Het SIS geeft geen extra toetsinschrijving voor pogingen aan TPS die al eerder aan TPS zijn toegestaan.

TPS koppelt het behaalde resultaat aan de componentOfferingassociation van de Toetsinshrijving, en het resultaat van alle extra pogingen aan een nieuwe componentOfferingassociation (via orgAssociationId gekoppeld aan de Toetsinschrijving).

**Comment by roelgrif** [comment]
De formulering is vooralsnog verre van waterdicht. Stel SIS stuurt poging 1 met attemptLeft = 1. TPS stuurt toetsresultaat poging 1 terug.
SIS stuurt vervolgens poging 2 met attemptLeft = 1 en tegelijkertijd poging 1 opnieuw met attemptLeft = 0 (wijziging/correctie). Valt dit onder de acceptabele werkwijzen? is niet per se in strijd met de bovenstaande formulering. Als het TPS daarna een resultaat met poging nummer 2 terugstuurt, is dat dan de extra poging op de originele poging 1, of de (nieuwe) extra poging op de latere poging 2? Ik hoop natuurlijk het laatste. Als het eerste gebeurt betekent dat dat het SIS eigenlijk geen mogelijkheid heeft om fouten te corrigeren, wat me zeer onwenselijk lijkt.

**Comment by JosVanderArend** [comment]
Het is wel een complexe situatie, die waarschijnlijk ook nog wel grensgevallen kent maar volgens mij hebben we afgesproken dat TPL wijzigingen zo goed/snel mogelijk verwerkt. Het uiterste moment is hierbij het moment dat de afname is gestart. Daarna kun je een inplande student niet meer terugtrekken. 
Dus als de tweede poging al is ingepland bij toetsinschrijving1 dan kan deze op tijd worden ingetrokken. Maar dan moet deze student voor toetsinschrijving2 wel opnieuw worden ingepland, en mogelijk kan dat niet meer. 

Ik zou dus zeggen dat het een acceptabele werkwijze is maar dat het mogelijk ook extra werk oplevert (opnieuw inplannen) en dat de student mogelijk niet kan deelnemen aan een geplande toetsafname. 
Beter is misschien toetsinschrijving1 te corrigeren met attempLeft=2.

**Comment by roelgrif** [comment]
Ja, maar het SIS weet natuurlijk niet of er op die attemptLeft = 1 (dus op een mogelijk door TPS te initieren poging 2) al iets van een planning is gedaan of niet. En het kan zijn dat b.v. bij geoorloofde afwezigheid bij poging 1 in het SIS logischerwijze een nieuwe poging aangemaakt wordt. Dat loopt wellicht anders bij het behalen van een voldoende dan wel een onvoldoende op die eerste poging. Stel dat het SIS onmiddellijk zou weten als er een poging 2 'onderweg' is, dan is het natuurlijk geen probleem, dan hoeft het SIS zelf niet een nieuwe poging 2 aan te maken, dan 'staat' hij er a.h.w. al (ontvangen van TPS). Maar met die attemptLeft benadering weet het SIS dat dus niet, alleen dat er misschien ooit een poging 2 van het TPS gaat komen, of niet. Terwijl het bij b.v. die geoorloofde afwezigheid gewoon moet, zo snel mogelijk opnieuw inplannen. Vandaar het 'zetje' vanuit het SIS. Het ophogen van attemptLeft naar 2 verbetert m.i. weinig aan die situatie.

**Comment by JosVanderArend** [comment]
Door de attemptLeft te verhogen en creëer je toch een extra poging bij een bepaalde Toetsinschrijving in flow 1. Een geplande deelname in flow 2 kan gewoon blijven, omdat de de toetsinschrijving niet is gecanceled.
Als het resultaat van deze deelname al binnen is bij het SIS dan is het geen verbetering in plaats van een nieuwe toetsinschrijving.

**Comment by roelgrif** [comment]
Nee, je creeert geen extra poging door de attemptLeft te verhogen. Je creeert alleen meer ruimte voor het TPS om mogelijk een extra poging aan te maken (2 ipv 1). Maar dat schiet dus niet op, want je weet als SIS niet of en hoe die ruimte gebruikt wordt. 
Een eventuele geplande deelname heeft nog geen corresponderende planbare toetsinschrijving in het SIS. Kortom het SIS zit 'op slot' en kan niks meer doen dan afwachten tot van die ene extra poging (2) of (in het geval van ophogen) van beide extra pogingen (2 en 3) resultaten terugkomen uit het TPS. Ik zou willen dat het SIS gewoon de volgende poging aanmaakt, naar het TPS stuurt, en het TPS het resultaat terugkoppelt op de door het SIS aangeleverde planbare toetspoging. Of het TPS dat cijfer 'realiseert' op een al eerder geplande toetsinschrijving (in flow 2-3-4), dan wel op een toetsinschrijving die pas gepland is na het aanleveren door SIS van die 2e poging, zou dan m.i. niet uit moeten maken.

**Comment by JosVanderArend** [comment]
Het gaat mis wanneer TPL al is begonnen aan het vullen van een bakje (en je zet nieuwe bakjes neer en haalt de bestaande bakjes weg): 
- een student is ingepland voor een zitting --> deelname terugtrekken, 
- een student is al begonnen met de toetsafname --> er komt een resultaat
- een student heeft de toets al gehad maar de beoordeling duurt nog --> er komt een resultaat

**Comment by roelgrif** [comment]
Daarom wil ik het eigenlijk direct weten als het TPS een bakje heeft gemaakt en van plan is het te gaan vullen (en niet pas als het resultaat er is). Dan kan ik *dat* bakje ook aan onze kant klaar zetten voor het opvangen.

**Comment by JosVanderArend** [comment]
Besloten is voor 1.0 het attemptLeft zoals bovenstaande te hanteren en indien SIS meer controle wil over het pogingenbeheer het dan attemptLeft=0 moet gebruiken.
Later zullen we bediscussiëren of er verbetering mogelijk en nodig is in de informatieverstrekking over de gemaakte planning vanuit TPL richting SIS (flow 5 uitbreiding), zie #153.
