### ISSUE TITLE
Voorstel meenemen rol corrector in OKE (Manon van Soest)

### ISSUE THREAD

**Issue by JosVanderArend** [NetwerkExamineringDigitalisering/NED-OOAPI#158]
Ingebracht door Manon van Soest (ROC Midden Nederland):

Probleem
Waar we nu tegen aan lopen bij het in gebruik nemen van de OKE EduArte-Remindo-SPL is dat de meeste data van het toetsmoment via de koppeling verloopt. Maar dat je als medewerker examenbureau toch elk toetsmoment moet openen en bewerken voor het aanmaken van correctierondes en het toevoegen van de corrector. Dit haalt het voordeel van het volledig laten verlopen van de koppeling weg.  In de bijlage staat een printscreen van de schermen en velden die nu nog ingevuld moeten worden voor de rol corrector.
[Voorstel inrichten corrector opm NvD.docx](https://github.com/user-attachments/files/17616728/Voorstel.inrichten.corrector.opm.NvD.docx)

Voorstel:
De wens is om extra handelingen in Remindo(SPL) te reduceren. Het voorstel is om een standaard toekennen een correctieronde met 1 of meer correctors, met een standaard nakijkverdeling. Hiermee wordt de werkwijze, automatisch standaard en enkel extra handeling(en) bij een exotische correctie. 

Met daarnaast wel de volgende vragen:
•	Kan een examen zonder autocorrectie, ook na de afname nog ingeregeld worden? (van standaard naar exoot veranderen?)
•	Kan de standaard instelling identiek voor alle scholen zijn of dient de standaard instelling van de school zelf leidend te zijn

**Comment by JosVanderArend** [comment]
Op het eerste gezicht lijkt dit een issue voor Remindo/SPL. Het feit dat dit wel werkt voor TOA geeft aan dat de OKE-koppelingen dit wel ondersteunen: Er is binnen de Deelname  (ComponentOfferingAssociation) de mogelijkheid om een Medewerker (Person) in de rol van beoordelaar/corrector (assessor) aan de Zitting te toe te wijzen. 

Als in dit issue wordt bedoeld om het aantal correctieronden vanuit TPL te kunnen bepalen en doorgeven aan TA, dan wordt dit niet ondersteund door OKE: Er is in flow 2 (en ook niet in flow 1) geen informatieoverdracht over het aantal geplande correctieronden. Je zou uit toegewezen correctoren kunnen afleiden dat er 1 of meer correctieronden zijn.

Het wijzigen van het aantal correctieronden en/of het toewijzen van correctoren na afloop van de toetsafname, zou eventueel kunnen gaan werken. Het nut en de noodzaak hiervan na toetsafname moet hierbij worden meegenomen/afgewogen. 
De meest voor de hand liggende oplossing lijkt deze aanpassingen in het TA-systeem (Remindo/SPL) te kunnen uitvoeren.

**Comment by hamrt** [comment]
Is besproken, voor nu geen verdere aktie vanuit kerngroep techniek
