### ISSUE TITLE
voorbeelden aanpassen in yaml met onze voorbeelden

### ISSUE THREAD

**Issue by mcginkel** [NetwerkExamineringDigitalisering/NED-OOAPI#16]

**Comment by JosVanderArend** [comment]
De volgende voorbeelden zijn bijgevoegd:[
Flow 2.1: PUT /offerings/{offeringId}
Flow 2.2: PUT /offerings/{offeringId}/associations/{associationId}

Flow 3.1: PATCH /associations/{associationId}
Flow 3.2 PATCH /associations/{associationId}

Flow 4.1: PATCH /offerings/{offeringID} TBD (PATCH ontbrreekt nog)

**Comment by rrutte** [comment]
Flow 2.4 en 2.5 ondersteunen via een Patch

**Comment by JosVanderArend** [comment]
@hamrt, in de opmerkingen van de attributen state en remoteState binnen Association (flow 2.2) staat dat state en remoteState moet worden gebruikt, met bij remoteState de opmerking "same as state, but not used. (unfortunatelly: mandatory).".

Als ik in de definitie van Association kijk dan is remoteState helemaal niet verplicht.

Maar als ik naar PATCH /associations/{associationId} kijk dan zie ik dat alleen remoteState mogelijk is.

Ik weet het even niet meer. Welke van state en remoteState moeten we waar gebruiken?

**Comment by hamrt** [comment]
To do: Flow 2.4 nog aanmaken inclusief voorbeeld (remoteState is alleen aanwezig in het voorbeeld (aanpassen) @hamrt 
FLow 2.5 voorbeeld toevoegen @JosVanderArend

**Comment by mcginkel** [comment]
allemaal resolved
