### ISSUE TITLE
add patch offerings endpoint

### ISSUE THREAD

**Issue by mcginkel** [NetwerkExamineringDigitalisering/NED-OOAPI#18]

**Comment by JosVanderArend** [comment]
Het endpoint PATCH /offerings/{offeringID} is nodig volgens Flow 4.1, zie https://github.com/NetwerkExamineringDigitalisering/NED-OOAPI/blob/main/doc/flow4.md#flow-41--send-attendance-en-offering-report-directly-automated-scored-tests

**Comment by hamrt** [comment]
done in in commit 4d6e610b9093f2252d6e2fcb57395f28ba258896
