### ISSUE TITLE
how to tackle flow 0

### ISSUE THREAD

**Issue by hamrt** [NetwerkExamineringDigitalisering/NED-OOAPI#20]

**Comment by rrutte** [comment]
Flow 0 is basically a GET on components. However, in Remindo and TOA components (tests) can be scoped by educations or departments. Is this an issue?

**Comment by rrutte** [comment]
GET on componentes is always in scope based on OAuth identification

**Comment by hamrt** [comment]
All components will be returned with additional attribute for licenced (toggle/bool) indicating whether the component is available for the institution. the components can be filtered based on ?licensed=true

**Comment by hamrt** [comment]
add code to the spec.yaml @JosVanderArend add the examples
