### ISSUE TITLE
Flow 1

### ISSUE THREAD

**Issue by hamrt** [NetwerkExamineringDigitalisering/NED-OOAPI#24]
Since flow 2,3 and 4 have been created we now need to tackle flows 0 - 1 - 5

**Comment by mcginkel** [comment]
First proposal for flow 1:

To make a proper selection of students and exams/test you almost need all information in a SIS. (students, registrations, studies, study plan, tests, previous results, etc etc). Basically the whole SIS database. Just exporting this and keeping this dat app to date in multiple systems is an expensive and error prone operation, and basically something a SIS is not happy to do.

What if we can make a first selection in the SIS or (store the queries) in the SIS: The planning tool can then request the list of tests/exams that need to be planned. For each selection/query the planning application can get/request the list of students that need to be scheduled. When available the SIS can also provide which test(s) are the instruments for this test/exam.

The planning application is responsible for the actual planning which student wil have a test at a particular moment(zitting). How that is done is up to the planningsapp. (the planning app can return this info so it appears in the SIS calendar/agenda)

The planningsApp will use flow 2,3 and 4 to schedule the tests/exams in detail and get results. In some situations that plannings app can "post process" the results and validate them into "final" results

The plannings app will return the results to the SIS using flow 5. in this flow the result are coupled to a student/registration for  a section/query from flow 0. The SIS will register the attendance and results.

**Comment by roelgrif** [comment]
Are you suggesting that flow 5 can be used in two ways:
* communicating from planning app to SIS the actuale planned schedule for the student/test (so without a result yet)
* communicating the finalized result from planning app to SIS *after* the planning app receives the result from the examination app?
So that would mean the result is optional, but the planned schedule is required?
A problem I see here is that the SIS never gets to know the session info (only the info per student - which means it is not normalized or important session info like building, room, etc. would be missed). 
Basically I doubt if this info is 'in scope' for planning app --> SIS .... if it is, wouldn't we need a flow 6 with session info to be presented to the students from SIS?

**Comment by mcginkel** [comment]
Besproken op 3 jan : techniek kern team:

* Plannen we een toets of een abstracter ding? We willen rekenen niveau 3 testen. welke toets exact is aan de plannings of afname app. 
* De sis kan al vastleggen welke toetsinstrumenten mogelijk gebruikt kunnen worden. 
* Kunnen we learning-outcomes gebruiken ?
* We zoeken naar een grove selectie in de SIS, met genoeg info zodat de planner details (zoals versie bij herkansing, andere versie bij speciale opleiding, andere versie bij special needs)
* De SIS moet wel updates sturen als de selectie verandert (studenten stoppen/starten opleiding)

* In het OER ligt vast welke learning-outcomes nodig zijn.
* We hebben een Learning outcome die we willen testen, daar zijn verschillende componenten voor die door verschillende componenten offerings werkelijk getoetst word.
* Peoplesoft: toets word als course gemodelleerd. Is dat flexibel genoeg ? als je course flexibel interpreteert wel.
* Relatie met kerntaken(/werkprocessen). wel generieker houden.

* Leaning outcomes word flexibel mee omgegaan. aan het SIS om dit in te vullen. voor communicatie naar de planner app is het wel een goede eenheid.

* Werkt dit ook voor formatieve toetsing?

**Comment by roelgrif** [comment]
Wat ik van mijn beoogde pilotschool begrijp is dat er een issue is als de selectie die vanuit het SIS met de planningstool uitgewisseld wordt in flow 1 vrij generiek is (dus b.v. opleiding en niet vak of toets). Als dan vanuit flow 5 resultaten op een toets terugkomen in het SIS, bij welke toets worden dan de resultaten weggeschreven? Momenteel is dit vaak handwerk van een functioneel beheerder, die na visuele inspectie van de Remindo toets bepaalt met welke toets in het OER (vastgelegd in het SIS) er een match is, en waar dan dus de resultaten op kunnen worden weggeschreven. Extra complicerend is dat sommige toetsen zowel voor een generiek vak als voor een keuzedeel geldig kunnen zijn. 
Hoe kunnen we dit oplossen? Hoe borgen we dat de toetsresultaten (zo geautomatiseerd mogelijk) in het SIS terecht komen zonder dat er 'handjes' of menselijke 'ogen' nodig zijn? Als op basis van brede selecties studenten (ontvangen vanuit het SIS) in de planningstool het plannen gestart wordt en de toetsen geselecteerd, hoe weet het SIS dan straks wat daarvan de mapping met het OER / de toetsboom is?

**Comment by EAvanJohn** [comment]
Een flow die ik hierbij voor me zie:
Bij de gegevens via Flow 1 moeten ook de beschikbare toetsen (met unieke key) meegestuurd worden van KRD naar planningstool. Dit zijn er op basis van de selectie 1 of meerdere. Bij meerdere toetsen bepaalt de school in de planningstool welke toets het betreft.
Als er een resultaat wordt ontvangen vanuit de toetsafname, dan weet de planningstool dus welke toets dit betreft. In flow 5 worden dan dus student + toets + resultaat teruggestuurd van planningstool naar KRD.

Of dit een realistische flow is, is mede aan de planningstools.

**Comment by hamrt** [comment]
zijn in stukken al afgehandeld
