### ISSUE TITLE
add enumerations 

### ISSUE THREAD

**Issue by hamrt** [NetwerkExamineringDigitalisering/NED-OOAPI#29]
Check enumerations on results e.g. 1.0 - 10.0

**Comment by JosVanderArend** [comment]
I see only these resulttypes in the specs, see https://netwerkexamineringdigitalisering.github.io/NED-OOAPI/specification/v5/docs.html#tag/component_offering_model:
-     pass-or-fail
-     US letter
-     UK letter
-     0-100
-     1-10
So, compared to this we need 3 extra values "DE grade", "0-10" and "0.0-10.0" in the enumeration (not using the value "1-10").

**Comment by roelgrif** [comment]
Is this based on the assumption that the actual grading will always be done by the exam applications? I can imagine a situation wherein that application would just return a score (x out of y, where x and y could be > 100), where the exam planning application (or even the SIS itself) should convert this to a real grade between 0.0 and 10.0 (or so). So maybe add a 'score' value (0-999?) but then we would need to be able to communicate the max score of the scale also, of course.

**Comment by EAvanJohn** [comment]
@JosVanderArend / @rrutte : what grade supports "OVG" or variations like a 10-point type from "zeer slecht" to "uitmuntend"? Or are they not supported in OKE?
@roelgrif: `Is this based on the assumption that the actual grading will always be done by the exam applications?`
The return of a result is part of the scope, return of a score (that needs to be converted) is not. That's a function not every SIS supports.

**Comment by roelgrif** [comment]
Which SIS does not support this, then? Where exactly has this scope been described? Is this the minimum set of all supported features in the SIS-es (which ones exactly then?) I'm not sure someone asked me about what is or isn't support in my own SIS.

**Comment by mcginkel** [comment]
???
Make distinction between score and result.
We need to decide if we have an enum or a flexible structure describing the scale in detail (min, max,decimal, list)

Hierover nakenken


2e probleem : waar versturen we de "resultValueType" en wat verwachten we dat er dan mee gebeurd

**Comment by hamrt** [comment]
scores en resultaten zouden uit elkaar getrokken moeten worden. 
Verwachte scores en maximale score hoe zou je om moeten gaan met de score?
Een score kan bestaan uit een:
* score die behaald is en;
* de maximale score 
Resultaat is het cijfer (welke waardering de student krijgt) 
* resultaatwaarde (resultvalue)
* schaal (resultvalue-type / scale)
* definitief (ja of nee) 
Deze waardes in de consumer van het result toevoegen?

**Comment by JosVanderArend** [comment]
Hier een poging om de begrippen Score en Resultaat te definiëren. 

**Score** is een individuele score, d.w.z. een score behaald door individuele toetsdeelnemer. De behaalde scores bij een toetsafname kan eenvoudig of complexe en meerledig zijn. Scores kunnen wijzigen n.a.v. aanpassingen in toetsinhoud, zoals aanpassing van sleutel, neutralisatie items, e.d. Alleen scores binnen dezelfde toetsafname zijn vergelijkbaar.
Synoniemen zijn Toetsscore, Afnamescore en 'Ruwe score'.
Soorten score zijn bijvoorbeeld ‘Aantal scorepunten', ‘Aantal goed', ‘Aantal opgaven', ‘Aantal gelezen’, ‘Benodigde tijd’, Vaardigheidsscore, Domeinscore, Onderdeelscore.

**Resultaat** van een toetsdeelnemer is een volgens specifieke schaal bepaald resultaat na normering van diens scores (ruwe scores). De behaalde resultaten bij een toetsafname kan enkelvoudig of meervoudig zijn. Resultaten kunnen wijzigen n.a.v. aanpassingen in de normering. Resultaten volgens dezelfde schaal zijn onderling vergelijkbaar.
Synoniemen zijn Referentiescore, Toetsresultaat en ‘Genormeerd resultaat’.
Soorten resultaat zijn bijvoorbeeld Eindcijfer, Schoolcijfer, Percentielscore, Functioneringsniveau, Toetsadvies, DLE, Referentieniveau, Goed/Voldoende/Onvoldoende, Geslaagd wel/niet.

**Comment by roelgrif** [comment]
Ziet er goed uit. Misschien nog iets noemen dat er in veel gevallen (wellicht niet in alle gevallen, b.v. als het gaat om benodigde tijd) sprake is van een maximumscore (die door een van de partijen bij de normering gebruikt kan worden c.q. gebruikt is). Voorbeeld: iemand heeft een score van 63 punten gehaald. Er wordt een item geneutraliseerd, maar de score van 63 kan gelijk blijven. Toch verandert de maximumscore van b.v. 92 naar 89 en daarmee krijgt de 63 wel een andere betekenis.

**Comment by EAvanJohn** [comment]
Qua afhandeling van scores: functioneel gezien ligt in Eduarte de schaallengte (het maximumscore) en de normering (eventuele correctiefactor) vast op de aan de opleiding gekoppelde "toets". Dat is vergelijkbaar met een papieren PTA/OER: je beschrijft voor de opleiding (geldend voor alle studenten) de toetsen en examens die worden afgenomen, met de bijbehorende schaal, weging en berekening van het eindresultaat. Hierin is geen ruimte voor individuele normeringen. Als er per toetsafname/-variant een ander maximum kan gelden, dan kunnen scholen dit in ieder geval niet kwijt in Eduarte. Omrekenen naar een resultaat kan dan niet in Eduarte plaatsvinden.

Veelal verzorgen de toetsafname-systemen zelf deze omrekening. Het lijkt mij raadzaam om voordat er (veel) tijd gestoken wordt in het nadenken over deze splitsing/optie, te vragen aan de deelnemende toetsleveranciers wie werkt met scores zonder interne omrekening naar een resultaat? Ongeacht of het een mogelijkheid is, maar worden er wel scores teruggeleverd of worden dat altijd resultaten? Of is die uitvraag al gedaan?

M.b.t. de eerdere vraag/opmerking over scoping: het terugkoppelen van een **resultaat** is in de eerste sessies met scholen, SIS- en planningsleveranciers en toetsleveranciers behandeld. Die scope zou in ieder geval voor versie 1 van de koppeling bevroren worden. Kan uiteraard wel op de backlog komen voor latere versie, indien relevant.

**Comment by roelgrif** [comment]
In PeopleSoft Campus Solutions is het wel degelijk mogelijk om resultaten (in een bepaalde schaal) te berekenen a.d.h.v. de behaalde score en een gegeven maximumscore, die per toets *zitting* verschillend kan zijn, ook al gaat het om de zelfde toets (immers, zelfs al hanteer je normaliter dezelfde maximumscore over de verschillende versies van een toets, dan nog kan b.v. een geneutraliseerd item bij de ene zitting leiden tot een lagere maximumscore terwijl op de andere zitting de originele maximumscore gehandhaafd blijft). In theorie zou het zelfs met een verschillende maximumscore per student kunnen (weet niet of dat in de praktijk gebruikt gaat worden), maar alleen al de mogelijkheid voor verschillende maximumscores per toetszitting lijkt me dat we dit niet moeten laten liggen. In het OER hoeft ook niet per se de maximumscore vermeld te worden lijkt mij: een formule als 1 + 9 * (score / maximum score) kan voldoende zijn, of zelfs gewoon de melding dat het eindresultaat in een 10punts schaal gegeven wordt (zonder te specificeren hoe dat resultaat precies vastgesteld wordt). Ik hoop dat er toetsleveranciers zijn die deze wijze van terugkoppelen ondersteunen, zo niet, dan verwacht ik dat wel voor de nabije toekomst. Maar inventarisatie is nooit verkeerd natuurlijk.

**Comment by EAvanJohn** [comment]
M.b.t. de OER zeggen we hetzelfde :-) Verschil tussen Eduarte en PSCS is dat in Eduarte alleen de OER gezet wordt, en in PSCS kan er per zitting/afname iets geregistreerd worden.

Mijn persoonlijke verwachting is niet dat men dit niet veel gebruikt/zal gaan gebruiken (in de nabije toekomst), maar laten we dit vooral uitvragen aan de toetsleveranciers en daarna aan de scholen. Ik heb er een apart issue (#33) van gemaakt voor het overzicht.

**Comment by roelgrif** [comment]
OK, maar heb je het nu over Eduarte T&R (heet dat zo?)? of over Eduarte KRD?

**Comment by EAvanJohn** [comment]
T&E (Toets & Examenlogistiek) heet de betreffende module. Zowel KRD als T&E werken niet op deze wijze met scores. T&E geeft momenteel geen extra opties bij het registreren van behaalde resultaten (of dus scores).

**Comment by roelgrif** [comment]
OK, dank voor het antwoord.

**Comment by hamrt** [comment]
WE nemen de lijst over 
pass-or-fail
US letter
UK letter
DE grade
0-100
0-10
0.0-10.0
aangevuld met onvoldoende - voldoende - goed (in het engels)

**Comment by hamrt** [comment]
fixed in 3586dce5b03f53ecff63b24d018b719c2a7510fe

**Comment by JosVanderArend** [comment]
@rrutte , kun je beter duiden wat de DE grade is, met name het waardebereik of de waardelijst van de resultaatwaarde?
Ik zie op wikipedia heel veel soorten maar welke is het, zie https://en.wikipedia.org/wiki/Academic_grading_in_Germany?
