### ISSUE TITLE
add elements to select components

### ISSUE THREAD

**Issue by hamrt** [NetwerkExamineringDigitalisering/NED-OOAPI#30]
define names for codesType to search specific components

**Comment by rrutte** [comment]
Suggestion: Base names on OO-API entities

- Program
- Course
- Organization

**Comment by mcginkel** [comment]
Proposal: add an array of labels/string to consumer. do nothing with other codes
The poetsafname application can add as many tags as needed, the SIS/planner can do an intelligent search to find them.

**Comment by hamrt** [comment]
GEt q= als query parameter + standaaard parameters die reeds gedefinieerd zijn
