### ISSUE TITLE
Uitvragen gebruik toetsscores

### ISSUE THREAD

**Issue by EAvanJohn** [NetwerkExamineringDigitalisering/NED-OOAPI#33]
N.a.v. #29 willen we aan deelnemende toetsleveranciers een uitvraag doen voor het gebruik van toetsscores  i.p.v. resultaten.
Toetsscore: het voor de toets behaalde aantal punten, met het maximaal aantal punten en evt. correctiefactor -> (behaald/maximaal)*correctiefactor = resultaat
Resultaat: het (op basis van de toetsscore) berekende cijfer/schaalwaarde als uitslag van de toets

**Comment by EAvanJohn** [comment]
Ik neem aan dat we dit via Hans laten lopen? Of heeft iemand van jullie de contactgegevens (mail) van de diverse leveranciers?

**Comment by JosVanderArend** [comment]
volgens mij is de formule voor het berekenen van het cijfer als resultaat als volgt:
cijfer = (behaalde score/maximale score) * 9 + correctiefactor
Waarbij correctiefactor default de waarde 1 heeft.

**Comment by EAvanJohn** [comment]
Die formule is inderdaad gebruikelijk bij het eindexamen VO, en is opgenomen in een wettelijke regeling voor het VO. Ik weet niet of in de mbo-keten met dezelfde formule wordt gewerkt. Maar daar moeten dan ook afspraken over gemaakt worden.

**Comment by EAvanJohn** [comment]
Nb. Ik begreep dat dit in het werkgroep-overleg van a.s. dinsdag aan bod komt.

**Comment by JosVanderArend** [comment]
Klopt!

**Comment by JosVanderArend** [comment]
Conclusies van de OKE werkgroep op 17 jan 2023 m.b.t. scores en resultaten zijn:
- Toetsafname doet altijd zelf de omrekening/omzetting van behaalde scorepunten naar het cijfer (resultaatwaarde).
- Zowel Toetsplanning als Deelnemerregistratie doen niets met de behaalde scorepunten (en dus ook niets met de maximumscore).
- Het resultaat in flow 3 is dus een resultaatwaarde volgens de resultaatschalen cijfer of GVO; deze resultaatschaal wordt in de toetscatalogus door de toetsaanbieder gedefinieerd.
- Het resultaat is soms wel en soms niet vastgesteld; vaststelling vindt in het laatste geval plaats binnen Toetsplanning. Vaststelling leidt eventueel (bij onregelmatigheden) tot aanpassing van het resultaat (0/onvoldoende of nietig), met wel/niet gevolgen voor mogelijke herkansing.
- Er zijn nog wat onduidelijkheden voor speciale situaties, zoals: 
  1. Wat wanneer het resultaat twee beoordelingen o.b.v. het bepaald niveau is
  2. Wat is de cesuur bij het cijfer?

**Comment by JosVanderArend** [comment]
Vraag: is er nog behoefte aan de scorewaarde (behaalde scorepunten) en maximumscore informatief mee te geven (optioneel)?

**Comment by EAvanJohn** [comment]
> vaststelling vindt in het laatste geval plaats binnen Toetsplanning
Er zijn scholen die nu onderzoeken om vaststelling in het KRD te laten plaatsvinden, buiten toetsplanning om. Juist omdat er ook afnames zijn die niet (expliciet) via OKE/toetsplanning lopen. Dus ik zou voor nu de optie open willen houden waar vaststelling plaatsvindt. Dat betekent dat "status" mee moet komen als attribuut in flow 3 en 5.

Cesuur maakt m.i. deel uit van de schaal.

Scorewaarde opnemen in bericht, zonder verplichting voor ontvangen dat deze getoond/verwerkt moet worden, is prima. Indien wel verplichting: dan niet opnemen. Anders moet er extra functionaliteit gebouwd worden zonder toegevoegde (functionele) waarde.

**Comment by JosVanderArend** [comment]
Vandaag (7 februari) heeft de OKE Kerngroep techniek in het overleg besloten om 2 optionele gegevensattributen in de Consumer van Result toe te voegen:
- rawScore/rawScorepoints (behaalde scorepunten)
- rawMaxscore/rawMaxscorepoints/rawScoreScalelength (maximum te behalen scorepunten)
En bij het gegevensattribuut score binnen Result duidelijk aan te geven dat het hier om de resultaatwaarde (resultValue) gaat, zoals dat er al in OOAPI staat dat deze gegevenswaarde moet voldoen aan de ResultValueType.
