### ISSUE TITLE
missing document endpoints

### ISSUE THREAD

**Issue by mcginkel** [NetwerkExamineringDigitalisering/NED-OOAPI#35]

**Comment by JosVanderArend** [comment]
Propsal for document-endpoint under a specific offering: /offerings/{offeringId}/{documentId}

**Comment by hamrt** [comment]
counter proposal  /offerings/{offeringId}/documents/{documentId} or even easier /documents/{documentId}

**Comment by rrutte** [comment]
I endorse the simples and most straightforward variant ie. /documents/{documentId}. Any system that uses this API with the correct document uuid has authenticated itself and the application that handles this request should use its regular authorization mechanismes to provide the document (or not). Any additional id's like course/offering/association id's in the request header makes this api less generic and draws attention away from the basic responsibilities of the application on imposing authorization restriction on every call based on it's own authorization schema's

**Comment by hamrt** [comment]
fixed in 42ce610ad63f77d1c7d2d3febda24871e6aba200
