### ISSUE TITLE
Is ID required in the body of the PUT and PATCH operations?

### ISSUE THREAD

**Issue by JosVanderArend** [NetwerkExamineringDigitalisering/NED-OOAPI#36]
In our current specification is the ID for Association in PUT/PATCH /associations/{associationId} and for Offering in PUT/PATCH /offerings/{offeringId} mandatory in the body of the request. But it is already the path parameter in the request.

The examples in our specs are without this ID-attribute. 
In the OOAPI specs itself is the associationId not present in the body of the request (see https://openonderwijsapi.nl/specification/v5/docs.html#tag/associations/paths/~1associations~1%7BassociationId%7D/patch).

@hamrt, I think this is not correct in our specs. What do you think?

**Comment by hamrt** [comment]
Agreed will take some rewriting of the spec. Just fixed
