### ISSUE TITLE
Missing the ComponentConsumer definition

### ISSUE THREAD

**Issue by JosVanderArend** [NetwerkExamineringDigitalisering/NED-OOAPI#37]
We defined the attributes extraTime, availablePersonalNeeds, exam, resultValueType, passFrom, retries, status and licensed within the Consumer object for Component. I don't see the Consumer object. See flow 0

Is is not present in the list of our consumers in https://github.com/NetwerkExamineringDigitalisering/NED-OOAPI/tree/main/specification/v5/consumers/MBO-toetsafname/V1.

**Comment by hamrt** [comment]
fixed with PR additional questions

**Comment by hamrt** [comment]
Waarom is er extraTime in een component? en waarom in een integer waarde? (of moet dat juist in de offering / assertion)
Waarom geven we retries mee in een component? Is het van belang hoevaak je die doet? of moet dat bij de student opgeslagen worden (in de assertion)
Willen we in de component ook de safety options meegeven zodat deze nog gekozen kunnen worden? (een attribuut die aangeeft welke mogelijkheden er zijn?)

**Comment by hamrt** [comment]
see #20 for complete flow

**Comment by JosVanderArend** [comment]
Is deze doorverwijzing naar issue #20 wel relevant, @hamrt ?
