### ISSUE TITLE
ComponentOffering in the Model in OAS3-definitions gives error message 

### ISSUE THREAD

**Issue by JosVanderArend** [NetwerkExamineringDigitalisering/NED-OOAPI#40]
On the page https://netwerkexamineringdigitalisering.github.io/NED-OOAPI/specification/v5/docs.html#tag/component_offering_model in the OAS3-definitions the ComponentOffering in the model does not appear.

Instead it gives the message "object ComponentOffering Recursive".

**Comment by hamrt** [comment]
Fixed with commit a9c3ba95851723d897f011cea8543bd288e0857a
