### ISSUE TITLE
Examples are not aligned with the specification

### ISSUE THREAD

**Issue by JosVanderArend** [NetwerkExamineringDigitalisering/NED-OOAPI#41]
I see some differences between de JSON-examples within the flows and the OAS3-definition:

1. In de examples within flow 0 in otherCodes within Component the codeType values "testSystem" and "testProvider" is used; these values are not available in the enum for codeType. Extensions are allowed but should use the prefix 'x-'.
Should we add these values to the enum or should we change these values in the example to  "x-testSystem" and "x-testProvider"?

2. In de examples within flow 0 in otherCodes within Component a uuid is used as value for organization. Since we don't support endpoints for organzations, a uuid as identifier for an organization has no value.
Should we delete this value or should we change this in an Organization object in the JSON-example?

3. If we add an example for employee-Person to the JSON-examples in flow 2 what kind of primaryCode should we use?
I would recommend the employee-number, but this is not an option (we can use the generic identfier for this). Another option is to use the e-mail address (option emailadress); and is this option "emailadress" (one 'd') spelled conform the specification?

**Comment by roelgrif** [comment]
1. I vote for x-testSystem and x-testProvider.
2. no idea (yet)
3. In the specification a person has an attribute "mail" instead of "emailaddress" whichever way spelled. Shouldn't we use that one?

**Comment by JosVanderArend** [comment]
A comment on the reaction on 3: I know and we use this mail attribute because this is mandatory. For each person these attributes personId, mail and primaryCode (and many more) are mandatory!
