### ISSUE TITLE
Vragen over nog niet aanwezige informatie

### ISSUE THREAD

**Issue by mcginkel** [NetwerkExamineringDigitalisering/NED-OOAPI#43]
Casus

- Eduarte stuurt als onderdeel van een zitting een locatie naar Remindo.
- Remindo kan de locatie niet verwerken, omdat daarvoor de locatie bekend moet zijn in Remindo.
- Remindo weigert het bericht en geeft een fout terug aan Eduarte.

Principe vragen:

- Mag een ‘toetsafname’ eisen dat bepaalde gegevens niet worden meegestuurd?
- Mag een ‘toetsafname’ aanvullende eisen stellen aan de gestuurde data en het bericht anders weigeren? (Dus niet: aanvullende eisen die voorwaardelijk zijn om de data juist te kunnen verwerken, het is evident dat dit soms het geval zal zijn.)

Voorgestelde uitgangspunten

- Alle verplichte en niet verplichte data die we in Eduarte beschikbaar hebben, sturen we mee als ze in het berichten format van de standaard passen, of zetten we om naar het in de standaard gedefinieerde datatype en/of de enumeratie.
- De ontvangende partij wordt geacht elk bericht dat voldoet aan de eisen van de standaard en de mogelijkheden daarvan benut te accepteren als geldig bericht en te verwerken.
- Als er aanvullende eisen zijn die voorwaardelijk zijn om de data juist te kunnen verwerken, dan mag dit niet leiden tot het weigeren van het bericht. De ontvangende applicatie dient zelf te zorgen dat de niet gewenste velden genegeerd worden of dat de fout afgevangen wordt en desgewenst aan de gebruiker wordt gemeld.

**Comment by mcginkel** [comment]
Wat hebben we afgesproken of besproken :
- locatie is meer een veld dat aangeeft waar het is, als er een functionele betekenis aan een locatie gegeven gaat worden (bv remindo gebruikt het voor beveiliging) moeten we dat explicieter aan de standaard toevoegen.
Voor een onbekende locatie verwachten we wel dat dat de flow niet stopt (en dus aanmaken)
- De gegevens van de leerlingen en afname leiders/surveillanten worden elke keer meegestuurd (laatste stand van zaken) en er word impliciet verwacht dat het afname systeem dat ook gebruikt.
We verwachten ook dat er niet eerst een sysnc van studenten/medewerkers geweest is, maar dat dit onderdeel van flow 2 is

grote lijn : zo min mogelijk de flow stoppen als het niet nodig is.  (muv verplichte velden)

In de bijsluiter willen we wel zo veel mogelijk beschrijven wat de verwachtingen zijn van de overgestuurde data

**Comment by hamrt** [comment]
@rrutte  check of zo is geimplementeerd en dan sluiten
