### ISSUE TITLE
Update body of PATCH /offerings/{offeringId}

### ISSUE THREAD

**Issue by boerrookhuiszen** [NetwerkExamineringDigitalisering/NED-OOAPI#47]
The body of `PATCH /offerings/{offeringId}` now is a copy of `PUT /offerings/{offeringId}`. I think we should:

- change the content type to `application/merge-patch+json` (like `PATCH /associations/{associationId}`) 
- remove required attribute from all properties
- update example for flow 2.5 (its now `{"state": "canceled"}`, in [the docs we have a better example](https://github.com/NetwerkExamineringDigitalisering/NED-OOAPI/blob/main/doc/flow2.md#example-of-request-delete-offering-zitting))

**Comment by hamrt** [comment]
fixed in PR
