### ISSUE TITLE
Flow 3/4 GET /documents/ ondersteunde response type

### ISSUE THREAD

**Issue by theovlastuin** [NetwerkExamineringDigitalisering/NED-OOAPI#55]
@hamrt Kun jij naar onderstaand issue kijken?

De huidige specificatie voor documenten is als volgt:

`get:
  summary: GET /documents/{documentId}
  operationId: listDocumentById
  description: Get the binary data from a docuemtn.
  tags:
    - documents
  parameters:
    - name: documentId
      in: path
      description: Document ID
      required: true
      schema:
        type: string
        format: uuid

  responses:
    '200':
      description: OK
      content:
        application/octet-stream: {}`

Dit duidt er op dat de inhoud van het bestand als body wordt terug gegeven. Om dit werkend te krijgen hebben we dit aangepast naar:

` responses:
    '200':
      description: OK
      content:
        application/octet-stream:
          schema:
            type: string
            format: binary`

Indien akkoord graag dit aanpassen in de standaard. De inhoud van de body is gecodeerd met Base64.

Paragin stuurt momenteel de documenten als response met content-type application/pdf. Als we dit in de standaard willen ondersteunen is het voorstel om de responses als volgt te definiëren.

`  responses:
    '200':
      description: OK
      content:
        application/octet-stream:
          schema:
            type: string
            format: binary
        application/pdf:
          schema:
            type: file`

Maar dan moeten misschien andere types ook ondersteund worden. We horen graag wat in de standaard wordt opgenomen.

**Comment by boerrookhuiszen** [comment]
Even een toelichting: vanuit Remindo serveren we de bestanden die via de documents endpoint worden aangeboden op dezelfde manier als "normale" bestanden. Wij voegen dus ook altijd een header met de "juiste" content-type mee, afhankelijk van het type bestand. Voor nu gaat het enkel om PDF-bestanden, maar ik weet niet of we dat in de standaard moeten voorschrijven.

Werkt het wellicht ook met een wildcard?
``` 
responses:
    '200':
      content:
        */*:
          schema:
            type: file
```

**Comment by hamrt** [comment]
hmm vreemd deze aanpassing zouden jullie al moeten hebben hij zat in de laatste commit van 2 dagen geleden 75a2d352726378d8d5f7fbc2beb523907b9f96e3
Ik heb nu ook een bundel toegevoegd, mogelijk heeft die jullie voorkeur
De oplossing die voor mij het meest logisch leek is aangeven dat het hier om een binary gaat in een string 
op deze manier kunnen verschillende binary formaten onderstuend worden (conform het voorstel ook van Theo. Ik heb ook nog een voorbeeld mee gegeven.

**Comment by hamrt** [comment]
fixed met check 11-5 (mail Theo)
