### ISSUE TITLE
Review flow 5

### ISSUE THREAD

**Issue by JosVanderArend** [NetwerkExamineringDigitalisering/NED-OOAPI#58]
Ik lees de volgende definities van resultDate en gradeDate:
resultDate: Date on which the candidate has performed the test/handed in the documents.
gradeDate: Date on which the assessment has taken place/has been finalized.

In OOAPI lees ik als deffinitie van resultDate: The date this result has been published.

Ik vind de betekenis van onze gradeDate dicht bij de OOAPI resultDate liggen. Ik dacht ook dat we hadden afgesproken om testDate (Date on which the candidate has performed the test/handed in the documents) toe te voegen naast de resultDate. Is er een speciale reden dat hiervan is afgeweken?

**Comment by roelgrif** [comment]
Zo wordt het wel heel verwarrend. De ResultDate is ook aanwezig in flow 3 en kan dus niet gaan over wanneer het in het SIS terecht komt. Want dat hangt af van wanneer het TPS klaar is met de dingen die daar nog moeten gebeuren. Het moment waarop het cijfer in het SIS terecht komt is bovendien m.i. geen kandidaat voor uitwisseling, maar kan gewoon door het SIS zelf (als audit stamp o.i.d.) weggeschreven worden.
Volgens mij zijn er twee belangrijke datums:
* datum waarop de toets afgelegd wordt (de datum van de toetszitting)
* datum waarop het resultaat toegekend wordt (de corrector heeft beoordeeld, zeg maar)
Als resultDate die tweede moet voorstellen, OK, maar dan hebben we m.i. geen gradeDate nodig maar een testDate. Bij digitale toetsing zullen de twee datums veelal gelijk zijn maar als er echt manueel beoordeeld moet worden dan zijn die twee datums echt verschillend, m.a.w. resultDate <> testDate.
Vinden we echter dat resultDate de datum van de toetszitting zou moeten zijn, dan is gradeDate toevoegen wel weer logisch , dat wordt dan de datum waarop de toets beoordeeld is.

**Comment by rrutte** [comment]
Ben het helemaal met Roel eens met daarbij de volgende aanvulling. Een toetszitting hoeft niet altijd op een specifieke dag te zijn. Dit kan ook een periode van een week zijn waarin een toets op een voor de student geschikt moment gemaakt kan worden of een tijdswindow waarin de student bijvoorbeeld een werkstuk kan inleveren. Daarom zou ik ook in flow 3 hetzelfde onderscheid naar testDate en resultDate maken. De daadwerkelijke testDate is absoluut van belang omdat er SIS'en zijn die validaties hebben of de student op het moment van toetsen wel onderwijs volgde etc. Ik zou met die testDate dus liever niet gaan gokken of aannemen, maar hem in de hele flow 3 en 5 opnemen.
