### ISSUE TITLE
Consumers in Swagger documentation of the YAML not correct

### ISSUE THREAD

**Issue by JosVanderArend** [NetwerkExamineringDigitalisering/NED-OOAPI#59]
In Swagger documentation of the YAML (https://netwerkexamineringdigitalisering.github.io/NED-OOAPI/specification/v5/docs.html) there are nog consumers included, not in the message content at the endpoints not in the data objects om the scheme components. 
This is something general because all the objects (Associaoiton, Result, Offering) that had a consumer defined this definitions is disappeared. And the ComponentOffering does have a consumer RIO-Offering!

**Comment by hamrt** [comment]
@JosVanderArend can you check it and close if its OK?

**Comment by hamrt** [comment]
•	Wordt bij de overdracht van de ComponentOfferingAssociation nu wel of niet de ComponentOffering expanded? En de personen (student/medewerker)? In flow 1 én flow 2?
•	Is het nu PUT /offerings/{offeringId}/associations/{associationId} of PUT /associations/{associationId} in flow 1?
•	Bij bepaalde stromen in specs het gebruik van expand aanduiden en benadrukken!
•	Heel veel consumers ontbreken in de [YAML-documentatie](https://netwerkexamineringdigitalisering.github.io/NED-OOAPI/specification/v5/docs.html#tag/component_offering_model) (inmiddels verholpen?)
•	Bij ComponentOffering in flow 1 (planbare toets) ontbreken de Consumer-attributen testsToBeUsed [in YAML-documentatie](https://netwerkexamineringdigitalisering.github.io/NED-OOAPI/specification/v5/docs.html#tag/association_model)!
•	Bij ComponentOfferingAssociation in [flow 1](https://github.com/NetwerkExamineringDigitalisering/NED-OOAPI/blob/main/doc/flow1.md#class-diagram-of-request-b-add-student-to-created-offering-zitting) (inschrijving) ontbreken de Consumer-attributen attempt,en attemptLeft, program- & courseOfferingAssociation in [YAML-documentatie](https://netwerkexamineringdigitalisering.github.io/NED-OOAPI/specification/v5/docs.html#tag/association_model)!
•	Consumer-attributen program- & courseOfferingAssociation horen niet bij Person in flow 1!
•	Bij ProgramOfferingAssociation in flow 1 (opleidingsinschrijving) ontbreken de attributen levelOfQualificatio, etc. in YAML-documentatie!

**Comment by roelgrif** [comment]
Wordt bij de overdracht van de ComponentOfferingAssociation nu wel of niet de ComponentOffering expanded? En de personen (student/medewerker)? In flow 1 én flow 2?
Wat mij betreft in flow 1: liever niet en kun je gewoon refereren aan een offeringId dat je in de ComponentOffering overdracht gedefinieerd hebt.

**Comment by hamrt** [comment]
PATCH nog toevoegen op de associations (Ronald)
nog een check of PUT /offerings/{offeringId}/associations/{associationId}  nog wenselijk is (Jos)

**Comment by JosVanderArend** [comment]
Reactie van Kees over het lange endpoint ( /offerings/{offeringId}/associations/{associationId}) t.o.v. het kortere ( /associations/{associationId}) in flow 2:

"Nee, omdat ik dan wel bij de offeringId kan gaat het goed.
Voor mij is het fijn om te kijken in welke context iets opgehaald word en of die context te verifieeren is. In dit geval is dat zo."

@hamrt, wat mij betreft gaan we dit endpoint in flow 2 ook inkorten en dan verdwijnt het lange endpoint uit de OAS3-definities.
