### ISSUE TITLE
Review Github-specs n.a.v. specificatiedocument

### ISSUE THREAD

**Issue by JosVanderArend** [NetwerkExamineringDigitalisering/NED-OOAPI#60]
Naar aanleiding van het specificatiedocument de volgende bespreekpunten:

- Bij ProgramOfferingAssociation in flow 1 (opleidingsinschrijving) ontbreken de attributen levelOfQualification, modeOfStudy, cohort, location, startDate, expectedEndDate, finalEndDate in [YAML-documentatie](https://netwerkexamineringdigitalisering.github.io/NED-OOAPI/specification/v5/docs.html#tag/association_model)!

- Bij ComponentOffering in flow 2 (zitting) hebben we de gegevens van duration, lastPossibleStartDateTime, startOptions, durationFrom, durationUntil, safety, offeringState, locationCode in de Consumer gedefinieerd. Spelen al deze gegevens geen rol in flow 1?
Btw: Voor flow 1 is er nog specifiek het gegeven testsToBeUsed toegevoegd.

- Er is een voorstel om in enumeratie SafetyType de waarde fixedLocation van te maken (ipv Fixed Location). En wellicht ook de andere waarden (SecuredComputer en Surveillance) met kleine letter laten beginnen.

- resultDate kan functioneel gezien toch niet verplicht zijn? 
Als er in flow 3 of 5 een attendance terugkomt (het resultaat komt later) dan kan de resultDate toch nog niet gevuld zijn? 
Mijn interpretatie was dat in resultDate de datum waarop wordt geconstateerd dat de student afwezig was. Zie ook “Class diagram of request A. Send attendance for student directly” van flow 3.

- levelOfQualification heeft toch al een enumeratie (EQF-niveau 1 t/m 8); In het specificatiedocument is dit gegeven gedefinieerd als MBO-niveau (MBO-niveau 1 t/m 4) zonder enumeratie. Wat is correct?

**Comment by hamrt** [comment]
Punt1 wordt verder uitgezocht voor de eerste punten de laatste 3 punten lijken logisch bij de association te liggen en worden voorgesteld om toe te voegen aan de consumer voor de association (Rene gaat dit punt verder uitzoeken) 
Voornaamste discussiepunt veel verschillende UUID's nodig voor offerings vs herhalen van gegevens uit standaard objecten (program/offering) hergebruiken (denormalisatie) die herhaald worden in de association.
Punt 2 checken op consistentie (Ronald)
Punt 3 resultDate wordt gebruikt om laatste mutatie van het gegeven (of het laatste moment waarop het cijfer is gegeven) door te geven testDate (het moment waarop de test is afgenomen, waarbij de slot dag van de toets geld als datum) ipv gradeDate (checken wat de gevolgen zijn) (Ronald)
Punt 4 voorstel om hiervoor EQF te gebruiken en deze op MBO niveau's te plaatsen alleen 1 t/m 4 nodig) (Ronald/jos in de documentatie)

**Comment by JosVanderArend** [comment]
Volgens mij is de status van 3: mijn aanname: "Mijn interpretatie was dat in resultDate bij afwezigheid van een resultaat de datum waarop wordt geconstateerd dat de student afwezig was (of dat is vastgesteld dat de aanwezigheid onbekend was, d.w.z. "unknown").". 

Wat betreft punt 4 zijn we helemaal over op de EFQ-niveaus 1 t/m 4 uit de range 1 t/m 8.

**Comment by hamrt** [comment]
volgens mij nu allemaal afgehandeld testDate nog toegevoegd.

**Comment by JosVanderArend** [comment]
Er staat in de YAML alleen nog wel bij testDate als type: "any <date-time> ", zie https://netwerkexamineringdigitalisering.github.io/NED-OOAPI/specification/v5/docs.html#tag/association_model.
Dat zou "string <date-time>" moeten zijn!

**Comment by hamrt** [comment]
goed gezien! Heb die testDate nu ook een type meegegeven.
