### ISSUE TITLE
Usage Consumer keys in header

### ISSUE THREAD

**Issue by rrutte** [NetwerkExamineringDigitalisering/NED-OOAPI#61]
The standard is ambiguous on this: [https://openonderwijsapi.nl/#/technical/consumers-and-profiles/](https://openonderwijsapi.nl/#/technical/consumers-and-profiles/)

Zelf zou ik een voorkeur hebben om bij een GET altijd de consumerkeys altijd mee te geven in de header en bij een PUT/PATCH alleen die consumerkeys mee te geven die geconfigureerd zijn voor de betreffende afnemer/het betreffende doel. Helemaal met een toenemend aantal consumers keys als de standaard uitgebreider gebruikt wordt.

**Comment by hamrt** [comment]
Lijkt me een prima oplossing. Misschien moeten we dan ook nog een manier verzinnen hoe we de configuratie informatie vastleggen. Vraag is nog wel wat de granulariteit wordt:
* per object 
* per object in combinatie met een partij 
* per object in combinatie met een partij en de methode (POST / PUT etc)

**Comment by roelgrif** [comment]
vierde optie: per object per methode?

**Comment by hamrt** [comment]
Toevoegen van keuzes en voorstel doen voor de documentatie en implementatie

**Comment by mcginkel** [comment]
xebic heeft dit niet meer nodig
