### ISSUE TITLE
TestComponentOffering flow 1 aangeven dat resultaten niet vastgesteld mogen worden door TPL

### ISSUE THREAD

**Issue by rrutte** [NetwerkExamineringDigitalisering/NED-OOAPI#62]
Flow 1: Offering/{offeringId} heeft momenteel niet de mogelijkheid om aan te geven dat het SIS niet wil dat resultaten door TPL vastgesteld gaan worden. Kunnen we in de consumer een attribuut finalResultAllowed (boolean) oid?

**Comment by JosVanderArend** [comment]
Ik vraag me af of dit gewenste functionaliteit is. Wij hebben het vaststellen van de resultaten als proces al ingekleurd bij Toetsplanning en Toetsafname. Eduarte (Kees) geeft aan dat het resultaat bij voorkeur al is vastgesteld. Volgens mij is dat ook de voorkeur zodat het asap kan worden gepubliceerd aan de student.

**Comment by roelgrif** [comment]
Bij NP maar ook collega instellingen worden cijfers pas in het SIS vastgesteld, en niet al in OT. 
Het lijkt me dat het standaard koppelvlak niet de business processen moet gaan vaststellen, maar de ruimte moet geven voor diverse werkwijzen.

**Comment by hamrt** [comment]
@hamrt in offering opnemen van finalResultAllowed (bool) 
description: depicting wether it is allowed to send either a final result or a perliminary result to the SIS. To allow for other results (e.g. temporary/intermediate) than final results to be sent to SIS.

**Comment by hamrt** [comment]
To allow for final results to be sent to SIS (in case of false)
