### ISSUE TITLE
activeEnrollment on Person (context?)

### ISSUE THREAD

**Issue by rrutte** [NetwerkExamineringDigitalisering/NED-OOAPI#63]
In edustandaard document staat als uitleg dat dit inhoudt dat student is ingeschreven voor toetsmoment. Zouden we niet als volgt kunnen definiëren?

- Student heeft een actieve programOfferingAssociation
- Employee heeft een lopend dienstverband
- Guest heeft actieve doelbinding

oid?

**Comment by JosVanderArend** [comment]
Ik neem aan dat dit bij programOfferingAssociation staat (in flow 1)?
Alternatieve tekstvoorstel voor Student heeft een inschrijving voor deze opleiding
Alternatieve tekstvoorstel voor Employee: heeft een directe relatie/binding met deze opleiding

**Comment by roelgrif** [comment]
Dit gaat al gebeuren bij GET /persons/{personId} dus zonder enige context. Dus wat is 'deze' dan?

**Comment by rrutte** [comment]
Kunnen we niet helemaal af van dit enrollment attribuut. De term is erg ambigue. Als je het leest weet je niet of bedoeld wordt of de person een actieve programOfferingAssociation, courseOfferingAssociation of componentOfferingAssociation heeft. Dan zou ik eerder verwachten een list met IDs van: activeProgramOfferingAssociations, activeCourseOfferingAssociations en active componentOfferingAssociations , maar ook dat is een lijstje waar je naar verwachting effectief erg weinig mee doet.

**Comment by roelgrif** [comment]
Op zich mee eens maar:
* requierd in OOAPI
* mijn voorstel om altijd 'true' te leveren (bij studenten) en eventueel false bij een medewerker, wellicht een redelijk compromis?
Je wisselt tenslotte alleen persoonsgegevens uit van actieve studenten.

**Comment by hamrt** [comment]
activeEnrollment is altijd true voor de person. Het gaat er om dat de student een inschrijving heeft op de instelling (betaald collegegeld) en dat de employee een medewerker is een actieve medewerker

**Comment by hamrt** [comment]
fixed in flow description
