### ISSUE TITLE
planbare toetsen en de rol van from/until

### ISSUE THREAD

**Issue by roelgrif** [NetwerkExamineringDigitalisering/NED-OOAPI#64]
De componentoffering heeft in flow 2 (toetszitting) natuurlijk wel datum/tijd maar in flow 1 (planbare toets) nog niet (daar gebruiken we juist het TPS voor, om die datums/tijdstippen te plannen).
In de componentOffering als object zie ik niet echt geschikte attributen om een periode aan te geven (schooljaar, semester, van - tot) ... (tenzij we startdatetime/enddatetime gebruiken wat me niet logisch lijkt - met tijdstippen - en wat ook niet door de documentatie gedekt lijkt te worden)
Dan ben je:
1. dus heel erg afhankelijk van de from/until parameters die TPS aangeeft, 
2. als SIS dus toch wel verplicht om intern een periode te bepalen (om te zien of deze toets geretourneerd moet worden bij een bepaalde from/until vraag vanuit TPS).
3. met een PUT helemaal in de problemen: welke toetsen van welke periodes ga je wel naar TPS sturen en welke niet? Of moeten we er van uit gaan dat een PUT alleen uitgevoerd wordt als er daarvoor een GET is geweest waarin we deze toets 'toevallig' geretourneerd is?

Ik dacht eigenlijk dat het idee was dat het SIS aangeeft dat bepaalde toetsen planbaar zijn in een door het SIS aangegeven periode (b.v. tussen de begin- en einddatum van het 3e semester, dat is tussen 1 februari en 15 april). Of zoiets.
Als we dat niet kunnen aangeven, hoe maken we dan de juiste selectie voor het TPS? En hoe beantwoorden we een GET met from/until als die periode gedeeltelijk overlapt met de periode die er in het SIS voor staat?
Voorbeeld: TPS vraagt from 1 april until 31 mei - geven we dan alle 3e semester toetsen en zo ja, hoe zorgen we dan dat die echt voor 15 april ingepland worden?

**Comment by hamrt** [comment]
endDatetime en startDatetime zijn leidende velden voor het teruggeven van de te plannen componenten uit het SIS bij de keuze van een from/until voor de planning van de toets. Mee nemen in de documentatie @JosVanderArend

**Comment by hamrt** [comment]
REtourneer alles wat mogelijk overlap heeft met de periode die geslecteerd wordt in de from until

**Comment by JosVanderArend** [comment]
Verwerkt in het specificatiedocument versie 0.8
