### ISSUE TITLE
Component object of verwijzing in PUT /offerings/{offeringId} in flow 1

### ISSUE THREAD

**Issue by roelgrif** [NetwerkExamineringDigitalisering/NED-OOAPI#65]
Het is mij niet duidelijk of het Component object expanded aangeleverd kan/moet worden bij een PUT /offerings/{offeringId} in flow 1 (vanuit SIS) om een planbare toets aan te leveren aan TPS.
Gezien de documentatie staat er 'component : string' maar aangezien het niet om een toets uit de toetscatalogus gaat maar om een planbare toets, waar is die string dan een verwijzing naar? Lijkt mij dat er een component *object* geleverd zou moeten worden. Aangezien er geen aparte PUT /components/{componentId} is voorzien, moet die dan toch *in* de offering passen?
Kijk ik in de OOAPI dan zie ik:
component:
        description: |
          The component that is offered in this componentoffering. [`expandable`](#tag/component_model)
          By default only the `componentId` (a string) is returned. If the client requested an expansion of `component` the full component object should be returned.
        oneOf:
          - $ref: './Identifier.yaml'
            title: componentId
          - $ref: './Component.yaml'
            title: Component object      
Dus als het een string was dan had het componentId moeten heten. Dit lijkt me onjuist in de documentatie. Correct?

**Comment by hamrt** [comment]
issue wordt geparkeerd tot na de sessie tussen CACI en Xebic en Deug

**Comment by roelgrif** [comment]
OK. Kan het verwerkt worden in een nieuwe versie van de documentatie?

**Comment by hamrt** [comment]
@JosVanderArend kan deze van de lijst?
