### ISSUE TITLE
Herkenbaarheid van binnenkomende calls

### ISSUE THREAD

**Issue by rrutte** [NetwerkExamineringDigitalisering/NED-OOAPI#66]
Bij ons komen alle calls binnen op ons integratieplatform. Uitdaging daarbij is dat we moeten herkennen naar welke applicatie we bijvoorbeeld bij een PUT de call moeten doorrouten. Of bij een GET aan welke applicatie we de vraag moeten stellen. Heeft iemand hier ervaring mee. Bij ons kwamen de volgende opties al langs die we allemaal niet charmant vinden:

1. Doelapplicatie in header meegeven
2. Base URL applicatiespecifiek maken met als uitdaging dat we veel basisgegevens calls naar meerdere applicaties doorgeven.

Heeft iemand ervaring met deze situaties en daar ook een mogelijke oplossingsrichting voor?

**Comment by hamrt** [comment]
Mijn eerste idee zou de HEADER zijn. Ik zit er zelfs over te denken of we de header mogelijk ook niet zouden kunnen gebruiken om selecties te doen ihkv consumers maar mogelijk gaat dat weer iets te ver.

**Comment by boerrookhuiszen** [comment]
Kan dit niet op basis van de authenticatie bepaald worden?

**Comment by rrutte** [comment]
> Kan dit niet op basis van de authenticatie bepaald worden?

Helaas niet. Wij kunnen bijvoorbeeld vanuit Osiris TestComponentOfferings en TestComponentOfferingAssociations voor meerdere applicaties ontvangen. Dit is in principe op te lossen middels een aparte authenticatie per doel applicatie, maar dat zou inhouden dat ook berichten voor basisgegevens zoals studenten/onderwijsinschrijvingen/groepen/groepsdeelnames per doel applicatie (dubbel) gestuurd zouden moeten worden en dat laatste proberen we te voorkomen.

**Comment by hamrt** [comment]
voorstel om dit nu uit te voeren op basis van identiteiten, authenticatie daarop en de bijbehorende scoping
