### ISSUE TITLE
Program properties

### ISSUE THREAD

**Issue by roelgrif** [NetwerkExamineringDigitalisering/NED-OOAPI#67]
Nu we hebben besloten ook het Program object te gaan gebruiken (en niet alleen de programOffering), moeten we zsm vaststellen welke properties we daarvan wel/niet gaan gebruiken. 
Voorstelletje:

wel:
programId
primaryCode
programType: program
name
abbreviation
description
teachingLanguage: nld
organization
modeOfStudy:  full-time (BOL), part-time (ODT), extraneous (examendeelnemer), dual training (BBL)
duration
firstStartDate
levelOfQualification
validFrom
validTo

niet:
addresses (kan per offering verschillend zijn)
organization (idem)
...

**Comment by hamrt** [comment]
hoi Roel even een vraag:
waarom neem je qualification Awarded mee? Het is niet verplicht? 
Waarom kies je hier voor een waarde die niet in de enum zit? Dat gaat dan weer tegen de spec in
Prima om de vertalingen te doen bij mode of study is iedereen daar mee OK? Dan kan ik kijken of ik dat nog ergens in de description er bij kan zetten
Ik zou organization als ID denk ik wel opnemen, dan weet je iig waar het programma vandaan komt, of zijn er programma's die het zelfde zijn maar dan over verschillende organisaties maw er is een N:M relatie tussen organizations en programs?

Ik kan de minimale set ergens in flow1 laten zien als voorbeeld. Ik zou de spec zelf niet uitkleden voor het programs object

**Comment by roelgrif** [comment]
Inderdaad, qualification awarded meenemen is niet zinvol. Ik heb hem geschrapt.
Technisch gezien is het mogelijk dat er meerdere organisaties zijn die dezelfde programs aanbieden. Weet niet of het heel vaak voorkomt maar prima, organization meenemen. Toegevoegd.
Verder eens, maar misschien in het document van Jos wel aanduiden welke we wel/niet van plan zijn te gebruiken.

**Comment by roelgrif** [comment]
Kan er vandaag een knoop hierover doorgehakt worden? De tijd dringt nu.

**Comment by JosVanderArend** [comment]
Het model schema component Program is inmiddels toegevoegd aan de OAS3-definities: https://netwerkexamineringdigitalisering.github.io/NED-OOAPI/specification/v5/docs.html#tag/program_model
In de specs worden de attributen zoals voorgesteld gespecificeerd.
