### ISSUE TITLE
Attributes missing in flow 5

### ISSUE THREAD

**Issue by rrutte** [NetwerkExamineringDigitalisering/NED-OOAPI#68]
Bij analyse op flow 5 tbv de integratie van SIS met TPL in het kader van PeopleSoftCS met OnTrac kwamen we er achter dat we nog een paar attributen missen.

1. Attempt -> Op welk attempt is het resultaat geboekt (in het geval dat TPS pogingen binnen een componentOfferingAssociation beheert.
2. OfferingName -> De naam van de componentOffering die TPL tbv TA heeft aangemaakt zodat in het SIS zichtbaar is (human readable) aan welke zitting de student heeft deelgenomen en waarin dus het resultaat tot stand is gekomen

**Comment by hamrt** [comment]
Wat is het voorstel hiervoor moet dit als een extra attribuut mee genomen worden in de consumer van de association in flow 5? 
Verdiepend op punt 1: 
- [ ] is het van belang dat het SIS hoort welke attempt dit is? 
- [ ] Het SIS voegt deze toch toe en is in principe toch leidend?
- [ ] Maakt het dan nog uit welk pogingnummer binnen komt? 
- [ ] kan het zo zijn dat het SIS aangeeft er zijn maximaal 2 pogingen. plan poging 1 en TPL komt terug met resultaat hier is het resultaat van de tweede poging? (de poging zit volgens mij op de assocation en zou daarmee niet zomaar van nummer kunnen veranderen)
Verdiepend op punt 2 
Heeft het SIS meerdere velden om bij te houden wat de offering name is? kortom kan het SIS op één toets aangeven dat het moment 1 toets A is en moment 2 toets B?
Ik snap overigens best dat we iets van de zitting mee terug willen sturen, dus we zouden het mogelijk moeten maken, vraag is alleen waar en onder welke naam OfferingName lijkt me niet handig immers die wordt al gebruikt. in flow 1 als de componentOffering naar TPL gaat. Is "executedOfferingName" een optie voor een naam?

**Comment by roelgrif** [comment]
A. Ja, het is m.i. denkbaar dat in het TPS (o.b.v. de examencommissie besluiten) een extra poging toegekend wordt, als er dan een cijfer binnenkomt bij het SIS is het wel handig om te weten of dat een correctie is op poging 2 die al in het systeem staat of een poging 3 die nog helemaal niet in het systeem staat.
B. Voor poging 1 geldt het zeker dat het SIS deze toevoegt. Voor een reguliere poging 2 verwacht ik dat ook wel maar voor een uitzonderings-poging 3, 4, 5 of hoger is het best mogelijk dat dit niet door het SIS geïnitieerd wordt.
C. Om te zien of er een resultaat overschreven moet worden of een nieuw resultaat naast gevoegd moet worden.
D. Het is de vraag of je het poging nummer als een sleutelwaarde voor de association moet zien in flow 1, of puur als informatief veld. In het laatste geval zou je een 1 op n relatie kunnen hebben tussen de heen gestuurde associatie en de terug ontvangen results. Want in de patch terug is de poging natuurlijk wel degelijk een sleutel (uniek samen met de associatie). Ik hoor graag of jullie dit een houdbare optie lijkt. Als het SIS de enige eigenaar is van het poging nummer EN dit moet als unieke sleutel gebruikt worden, dan weet je in het Result altijd wat je terugkrijgt en is de toevoeging niet nodig.

**Comment by hamrt** [comment]
De grote vraag in deze is dan waar houden we de poging vergeven bij en wie is daar verantwoordelijk voor?
Ik kan me voorstellen dat elke poging geregistreerd dient te worden en daarmee in het SIS terecht komt.
Als dat zo is dan kan het SIS dus ook een nieuwe association aan maken voor de volgende poging en loopt alles synchroon. (ik kan me overigens nog wel voorstellen dat je ergens aan wilt geven de hoeveelste poging iets is maar dat is enkel informatief)
Als we meerdere pogingen toelaten vanuit TPS naar SIS moet er ene array met resultaten naar de overkant. Dat kan maar dat heeft technisch wel wat voeten in aarde en zit nu niet in de spec. Ik zou die route niet willen begaan. Je wilt niet plots in het SIS van poging 1 naar poging 5 kunnen gaan zonder tussenliggende resultaten (ik neem aan dat er ook ergens iets van verantwoording .traceerbaarheid) moet zijn.
Is dit nog een punt voor discussie?

**Comment by JosVanderArend** [comment]
@rrutte, kun je nog beter aangeven waarom de naam van de zitting (offeringName of executedOfferingName) bij het studentresultaat in het SIS moet worden vastgelegd?
Het SIS hoeft dit niet te weten voor de pogingenadministratie en niet voor het laten plannen van een nieuwe variant, toch? 
Is dit meer dan archivering en zit er specifieke informatie in deze naam van de zitting, die je nog niet hebt?

**Comment by rrutte** [comment]
> @rrutte, kun je nog beter aangeven waarom de naam van de zitting (offeringName of executedOfferingName) bij het studentresultaat in het SIS moet worden vastgelegd? Het SIS hoeft dit niet te weten voor de pogingenadministratie en niet voor het laten plannen van een nieuwe variant, toch? Is dit meer dan archivering en zit er specifieke informatie in deze naam van de zitting, die je nog niet hebt?

Vanuit SIS gebruikers bestaat behoefte om bij een resultaat te weten als er twijfels zijn over het resultaat en/of de omstandigheden te weten vanuit welke zitting het resultaat behaald is. Daarom is de naam van de zitting zoals die in TPS nodig om in TPS en/of TA die zitting te kunnen opzoeken. Als je deze informatie niet hebt wordt het veel lastiger om de juiste zitting te vinden.

**Comment by roelgrif** [comment]
Wat doen we nu? Toevoegen? Morgen moeten we het ontwerp voor ons SIS finaliseren.

**Comment by hamrt** [comment]
Attempt zit al in association die zou ik niet nog eens mee nemen in het resultaat. de offering is toegevoegd

**Comment by hamrt** [comment]
@roelgrif en @rrutte als in lijn dan graag sluiten

**Comment by roelgrif** [comment]
Wat je zegt over het attempt klopt alleen als het uitgangspunt is dat:
* de Deelnemersregistratie eigenaar is van het volledige pogingenbeheer en TPS daar dus niets over te zeggen heeft
* het attempt een key value is in de association en niet een informatief gegeven.
Dat vind ik nogal zware consequenties. 
Ik kan me een optie voorstellen waarbij het SIS 2 pogingen toestaat, maar alle uitzonderingen van studenten die om welke reden dan ook extra herkansingen mogen doen van de examencommissie direct in het TPS geregistreerd worden. Zodat je niet voor elke extra poging eerst terug moet naar het SIS om daar de nieuwe poging aan te maken, uitwisselen, etc. etc. 
Lijkt me dat hier nog keuzes in gemaakt moeten worden.

**Comment by roelgrif** [comment]
Net zoals de offering in flow 1 een andere offering is dan de offering die je zojuist in flow 5 hebt toegevoegd, kan dus het attempt in flow 1 ('1e poging aan de beurt', '2e poging aan de beurt') een andere inhoud hebben dan het attempt in het Result in flow 5 ('2e poging afgelegd', '3e poging afgelegd'). 
Ik zeg niet dat het zo moet (of gezien vanuit het SIS niet anders zou kunnen) maar kan me voorstellen dat het voor gebruikers van een TPS makkelijker werken is, als het op deze wijze ondersteund kan worden.

**Comment by JosVanderArend** [comment]
@roelgrif en @rrutte, na de eerdere toevoeging van attributen en herformulering van flow 5, kunnen we dan dit issue sluiten?

**Comment by hamrt** [comment]
@roelgrif geeft OK

**Comment by rrutte** [comment]
Agree
