### ISSUE TITLE
Safety enum in flow 2 ooapi/offerings is niet consistent

### ISSUE THREAD

**Issue by rrutte** [NetwerkExamineringDigitalisering/NED-OOAPI#69]
In de spec staan de enumwaardes voor safety:

- SecuredComputer
- Fixed Location
- Surveillance

Wat is de standaard notatie voor enumwaardes? Met of zonder spaties?

Overigens heeft Remindo op dit moment "Secured Computer" als enumwaarde geïmplementeerd.

**Comment by JosVanderArend** [comment]
Deze waarden zijn in overeenstemming met andere waarden in enumeraties gebracht, kleine begin letter en camelCase. 
De waarden zijn nu in de OAS3-defs: "securedComputer", "fixedLocation" en "surveillance", zoals in consumers van Component, zie: https://netwerkexamineringdigitalisering.github.io/NED-OOAPI/specification/v5/docs.html#tag/component_model.

In de specs inmiddels ook aangepast!
