### ISSUE TITLE
Describe security via oauth & scopes

### ISSUE THREAD

**Issue by mcginkel** [NetwerkExamineringDigitalisering/NED-OOAPI#7]
On the project pages we should refer to the standard used by oauth. if there are choices to be made : describe them

**Comment by rrutte** [comment]
Token ophalen bij partij waar je gegevens vandaan haalt (GET) of heen stuurt (PUT)

Welke OAuth2.0 onderdelen gebruiken we?
- Access Token URL
- Client ID (uit te geven per tenant, zodat je zeker weet dat data niet aan verkeerde tenant aangeleverd wordt)
- Client Secret

Gebruik  ontvangen token bij API:
- Send as basic Auth header

**Comment by mcginkel** [comment]
So lets talk about scope:

I would secure every endpoint with a oauth token with a NED specific scope (example ned:flow2). and then separate scopes per endpoint/flow. so I can give a partner an auth token to use flow 2,3 and 4 but not 0 or 6.

We have  a strong preference to add scopes, so we can exchange clientid/secrets per partner, also if  the use other api's then this one.

**Comment by mcginkel** [comment]
proposed scopes:
MBO-toetsafname_Flow2
MBO-toetsafname_Flow3
MBO-toetsafname_Flow4
MBO-toetsafname_Flow0

**Comment by hamrt** [comment]
new proposal 1 scope voor 2,3,4 en mogelijk ook voor 1 en 5 
MBO-toetsafname
MBO-toetscatalogus voor flow 0

**Comment by hamrt** [comment]
extra check do we need to comply with edukoppeling for this and if so what does that entail

**Comment by roelgrif** [comment]
I sure hope not.

**Comment by rrutte** [comment]
Scopes nog naar engels
OAuth2.0 validatie en koppeling aan juiste instantie/tenant door uitgevende partij
