### ISSUE TITLE
ResultValueTypes zijn wel bekend als enums, maar waardes daarbinnen zijn nog niet gespecifieerd.

### ISSUE THREAD

**Issue by rrutte** [NetwerkExamineringDigitalisering/NED-OOAPI#70]
We hebben wel de enums vastgelegd voor resultValueType, echter de waardes binnen elke resultValueType zijn volgens ons nog niet hard gespecifieerd.

**Comment by JosVanderArend** [comment]
Wat bedoel je hiermee precies?
Dat de toegestane resultaatwaarden voor het veld score zijn? 
Dat staat redelijk omschreven in tabel 4.1.D: Enumeratie ResultValueType op pagina 54 in de specs.

Of bedoel je dat het in de flows op Github beter moet worden gedefinieerd?

**Comment by roelgrif** [comment]
Ik denk dat je gelijk hebt, volgens mij kunnen we met tabel 4.1.D verder.

**Comment by hamrt** [comment]
Kan dus afgevoerd worden op basis van deze conclusie? zo ja dan graag ook op closed zetten
