### ISSUE TITLE
Issues met ad-hoc en ondersteunende flows

### ISSUE THREAD

**Issue by rrutte** [NetwerkExamineringDigitalisering/NED-OOAPI#71]
1. Groups

Als TPS kunnen we niet overweg met de huidige group api's omdat deze uitgaan van de actuele stand. De applicatie gaat momenteel volledig uit van groepen en groepsdeelnames die beide ingangs/afloopdatums kunnen hebben. Hoe gaan we hier mee om? 

2. Studenten en onderwijsinschrijvingen

Basisgegevens willen gebruikers toch aanwezig hebben in OnStage en niet op afroep. Kunnen we gebruik maken van de volgende api's? Of zouden we dat buiten OKE, maar binnen OO-APIV5 kunnen doen?

- PUT persons/{personId}
- PUT associations/{associationId} voor programoffering associations met programoffering en program expands.

**Comment by hamrt** [comment]
Kun je dit verder toelichten,? Zijn dit 2 losse issues?

**Comment by roelgrif** [comment]
Ja, 2 losse issues. Het issue mbt Groups zorgt ervoor dat de development hiervoor in pilot 2 even on hold staat (aan beide kanten volgens mij) dus wel graag een oplossing morgen. Met de programoffering en person zaken kunnen we wel verder (een GET is tenslotte supported) dus dat is meer een user story aan de kant van OT.

**Comment by hamrt** [comment]
Het tweede deel van de vraag verder uitgewerkt. Er zijn nog een aantal onduidelijkheden: 
1. waarom is organization zo uitgebreid meegegeven in de flow2a 2? GET /ooapi/associations/{associationId}?expand=offering.program
ik ging er eigenlijk vanuit dat we alleen de program wilden expanden nu wordt ook organization expanded is dat wel wenselijk?
2 wat is de betekenis van cohort in de consumer van deze flow en waar zou deze matchen met reeds bestaande objecten? (ik kan me zo voorstellen dat het  cohort hoort bij de offering en dat dit dan het academicSession element is van de cohort?

**Comment by rrutte** [comment]
@hamrt 

1. Een program of programOffering is voor een toetslogistiek systeem contextloos als je niet weet welk onderwijsteam verantwoordelijk is voor de offering/program en bommem welk cluster/factulteit/instituut/sector/school dat team valt. Je wilt niet de hele organisatiestructuur van de onderwijsinstelling weten, maar alleen dat deel dat relevant voor je is. Bij een PUT is het handiger om dat mee te nemen dan alleen de ID's op te nemen en dan gelijk weer een GET ../organizations/{Id} te moeten doen.

2. cohort is het beginjaar van het curriculum dat hoort bij de programOfferingAssociation. Stel een student wordt in het derde jaar overgezet middels een opleidingsblad van het kwalificatiedossier naar een kwalificatie (uitstroomrichting) dan is ook op die programOfferingAssociation nog steeds het cohort het beginjaar van de inschrijving op het kwalificatiedossier. Dit kan nog gecompliceerder als de student in het tweede jaar is ingestroomd vanuit een andere onderwijsinstelling. Dan is het cohort niet het jaar dat je begonnen bent op de onderwijsinstelling, maar het cohort van een jaar eerder (en in het echt kan dit nog complexer zijn). Het is dus niet gerelateerd aan academic session, maar is meer OER gerelateerd.

**Comment by roelgrif** [comment]
1. Is er een organization object in scope dan? Ik lees er niets over in de documentatie. Ben er tot nu toe van uit gegaan dat we alleen de naam van de organization terug geven maar dat is niet terecht, blijkt nu (IdRef/Groep). Welke attributen van het organization object zou je dan willen uitwisselen? Moeten we dat niet gaan vastleggen dan?
2. eens.

**Comment by hamrt** [comment]
ad 1 organization endpoint toevoegen met een beperkte set, binnen ad hoc. toe te passen met in het voorbeeld alleen de 5 verplichte velden
ad 2 cohort moeten we nog verder uitwerken

**Comment by hamrt** [comment]
op de programOffering consumer cohort toevoegen als string? Elke instelling / school kan hierbij kiezen voor een eigen formaat. 
daarmee wordt voldaan aan huidige inrichting. (mogelijk na pilot nog verder uitdiepen)

**Comment by hamrt** [comment]
@rrutte kun jij checken of deze oplossing zo voldoet
