### ISSUE TITLE
Afspraken t.a.v . niet aangeleverde data

### ISSUE THREAD

**Issue by rrutte** [NetwerkExamineringDigitalisering/NED-OOAPI#72]
Aanlevering van attributen (en verwerking daarvan) die geen waarde hebben kan op verschillende manieren. 

- "attribuut": null,
- "attribuut": "",
- ~~"attribuut"~~
- "listattribuut": [ ],
- "listAttribuut": null
- ~~"listattribuut"~~

Gegeven een paar ervaringen met de Remindo OO-API api's lijkt het ons goed om hier aandacht aan te besteden. Op basis hiervan kan een partij een generieke OO-API ondersteuning aanbieden. Welke manieren ondersteunen we binnen OO-API?

- edit obv opmerking Roel

**Comment by roelgrif** [comment]
Bedoel je met de derde optie dat het attribuut helemaal niet genoemd wordt? 
Daar ben ik voor. Dat kan dan ook met het listAttribuut toch?

**Comment by rrutte** [comment]
Toevoeging vanuit Zalando specs: [https://opensource.zalando.com/restful-api-guidelines/#123](https://opensource.zalando.com/restful-api-guidelines/#123)

Deze stelt null en weglaten gelijk aan elkaar en zegt dat beide opties beschikbaar zouden moeten zijn

**Comment by boerrookhuiszen** [comment]
Als ik de Zalando specs goed begrijp, dan mag je niet zomaar `null` gebruiken, maar moet in de spec specifiek zijn aangegeven dat een attribuut nullable is. Maar als het wel mag, dan moet het dus dezelfde betekenis hebben. Een lege string `""` heeft wel echt een betekenis en is in principe goed, ook als het attribuut required is.

Ik denk niet dat het toegevoegde waarde heeft om overal `nullable` toe te voegen, of wel?

Overigens iets om in de gaten te houden voor onze PATCH-calls: `The only exception to this rule is JSON Merge Patch [RFC 7396](https://tools.ietf.org/html/rfc7396)) which uses null to explicitly indicate property deletion while absent properties are ignored, i.e. not modified.`. 

Overigens was de aanleiding van dit punt volgens mij de lege description in GET components die wij teruggeven als we geen description hebben, omdat hierbij is aangegeven dat deze non-empty moet zijn. 
<img width="673" alt="image" src="https://github.com/NetwerkExamineringDigitalisering/NED-OOAPI/assets/106390546/e7475ce7-bd22-40c9-9995-2d90af215dce">

Wij geven dit nu terug als volgt:
```
"description": [
   {
      "language": "nl-NL",
      "value": ""
    }
]
```
Maar hij is niet verplicht, dus `description` in dit geval weglaten mag ook? Moeten we hier explicieter in zijn?

Dit mag in ieder geval niet (want non-empty)
```
"description": []
```

**Comment by hamrt** [comment]
Mee nemen naar OOAPI werkgroep om dit kort te sluiten

**Comment by JosVanderArend** [comment]
Ik weet vanuit andere OAS3-definities dat er bepaalde systemen zijn die bij niet verplichte velden graag nullable op true hebben omdat ze dan zonder tussenstap de code kunnen laten genereren.

**Comment by hamrt** [comment]
beschrijf een PATCH waarbij we de description als attribuut weg kunnen gooien voor de PUT wordt alles overschreven en daarmee kan ook een lege description worden meegegeven.

**Comment by hamrt** [comment]
Voorbeeld toevoegen met de manier waarop we met de elementen uit het language typed string omgaan en de manier waarop we met arrays (gewonen en non-empty) om willen gaan. Aanvullend beschrijven dat "" als lege string is toegelaten.

**Comment by hamrt** [comment]
Invoeren in technisch document

**Comment by JosVanderArend** [comment]
Afsluiten
