### ISSUE TITLE
Wat is eigenlijk een programOfferingAssociation?

### ISSUE THREAD

**Issue by rrutte** [NetwerkExamineringDigitalisering/NED-OOAPI#73]
Het lijkt me goed om een duidelijke definitie te hebben van een programOfferingAssociation.

Als je kijkt naar MBO/HO zou mijn voorstel zijn:

- MBO: Opleidingsblad
- HO: Jaarinschrijving

Voordeel van dit niveau is dat de informatie binnen een opleidingsblad/jaarinschrijving eenduidig is ten opzichte van het ondersteunen van een programOfferingAssociation op volledige onderinschrijvingniveau waarbij niet duidelijk is wat de begindatum van bv een opleidingscodewijziging is.

**Comment by roelgrif** [comment]
Opleidingsblad/Inschrijvingsoverzicht, zou ik dan zeggen. Want sinds het afschaffen van de onderwijsovereenkomst zijn ook opleidingsbladen niet meer verplicht, maar zijn de ROC's wel gehouden aan de studenten te informeren over de actuele stand van hun inschrijving zodra daar een wijziging in komt.

**Comment by JosVanderArend** [comment]
Ik heb dit object in de specs "Opleidingsinschrijving" genoemd. Mooie samenvoeging!

**Comment by hamrt** [comment]
ondervangen door het toeveogen van sequenceCode in de consumer op association
