### ISSUE TITLE
Hoe om te gaan met aanwezigheid in flow 3 and flow 5?

### ISSUE THREAD

**Issue by JosVanderArend** [NetwerkExamineringDigitalisering/NED-OOAPI#76]
We hebben in flow 3 en 5 een attribuut attendance met enumeratiewaarden: notKnown, notPresent, notStarted, notFinished en present. Zijn dit valide waarden in beide flows?

**Comment by hamrt** [comment]
Alle waardes kunnen voorkomen. Conform het overzicht uit de tabellen. elk systeem moet er tegen kunnen dat deze waardes binnen komen. De business rules worden intern binnen de instelling vastgelegd.
