### ISSUE TITLE
Program is missing otherCodes for CreboCode

### ISSUE THREAD

**Issue by rrutte** [NetwerkExamineringDigitalisering/NED-OOAPI#77]
We ontdekten dat in documentatie tbv programOfferingAssociation de expand op Program nog een otherCodes sectie met daarin codeType "educationCode" en daarin crebonummer/keuzedeelnr

**Comment by roelgrif** [comment]
opleidingscode is (sinds kort) de algemene term voor crebocode (bv 25123) keuzedeelcode (bv K1234) of certificaatcode (bv C0123). Maar verder eens.

**Comment by JosVanderArend** [comment]
Betekent dit dat je graag attribuut otherCodes binnen Program zou willen gebruiken?

**Comment by roelgrif** [comment]
Tenzij je een andere manier weet om ergens binnen ProgramOfferingAssociation / ProgramOffering / Program te kunnen uitwisselen welke crebo/opleidingscode de student volgt, lijkt me wel ja.

**Comment by roelgrif** [comment]
In beide objecten staat het in de documentatie momenteel doorgestreept (alleen heet het in het Program otheCodes  ipv otherCodes). Maar inderdaad is het passender in het Program.

**Comment by hamrt** [comment]
RIO gebruikt opleidingsCode (vertaling educationCode) toevoegen in lijst of hernoemen
