### ISSUE TITLE
person en programOfferingAssociation attributes vragen

### ISSUE THREAD

**Issue by rrutte** [NetwerkExamineringDigitalisering/NED-OOAPI#78]
Bij het doorlopen van flow 1 tussen CACI en Xebic konden we de volgende aspecten niet mappen.

Persoon:

- personalNeeds. Er wordt best wel veel ad-hoc gepland. Het zou fijn zijn als in dat geval met de person ook de actuele stand aan personalNeeds mee zou komen om bijvoorbeeld de juiste oefentoets te kunnen selecteren.

programOfferingAssociation:

- state: bij het doorgeven dat een programOfferingAssociation kan je alleen aangeven dat die beëindigd is door in de consumer de definitieve einddatum vast te leggen. Het zou transparanter zijn als je ook de state op "finished" zou kunnen zetten.
- Je weet van de programOfferingAssociation niet wat de context is. Vanuit Osiris kan dit bijvoorbeeld een opleidingsblad 1.1, vanuit PeopleSoft zou het loopbaannummer meegegeven kunnen worden. Zou een otherCodes sectie op de programOfferingAssociation hiervoor gebruikt kunnen worden?

**Comment by hamrt** [comment]
@rrutte, ik dacht dat we personal needs niet op de persoon mochten zetten omdat die konden verschillen per soort toets. In principe zouden we de ruimte kunnen nemen om het bij de persoon toe te voegen. De vraag is dan weer wel of je het op de association moet laten staan. Als beide welke geldt dan? Ik zou zeggen die in de association, dit vraag wel om meer werk aan de kant van de planning.

De vragen rondom programOfferingAssociation zouden wat mij betreft nog iets verduidelijkt moeten worden. 
In principe zit er een status op association. Waarom wordt die niet gebruikt, of is die niet voldoende? Wat is het wijzigingsvoorstel? een extra status opnemen Finnished? Dat moet lukken. 

De vraag over context is voor mij niet duidelijk, wat is dat? een SBO code waarnaar verwezen wordt (in het kader waarvan de opleiding gedaan wordt?

**Comment by rrutte** [comment]
@hamrt personal needs bij de toetsinschrijving zijn gerichter dan de personal needs vastgelegd op de person, maar dat laatste helpt wel om bij bijvoorbeeld proefexamens al rekening te kunnen houden met aspecten als extra tijd.

programOfferingAssociation:

Als je middels een PUT mutaties op programOfferingAssociations gaat doorgeven is het handig om iets meer over de state van die association te weten. In het HO is een jaarinschrijving een jaarinschrijving en die loopt automatisch af per 31-8 als deze niet via Studielink verlengd wordt. 
In het MBO het je een onderwijsinschrijving waarbij bij mutaties een mutatieblad wordt toegevoegd. Dit mutatieblad heeft een volgnummer binnen een onderwijsinschrijving. Bijvoorbeeld, origineel 1.1 en bij een wijziging van de opleidingscode gaat deze naar 1.2. Anders dan in het HO kan je middels zo'n mutatieblad ook van opleiding switchen. Dit maakt het erg handig om in het onderwijslogistiek systeem te weten wat het opleidingsbladnummer is.

Hetzelfde geldt voor de state. In principe kan je aan de definitieve einddatum in de consumer op de Association zien wat de finalEndDate is, maar het zou handig zijn om ter ondersteuning daarvan in het reguliere object ook een association state "finished" te hebben.

**Comment by JosVanderArend** [comment]
We hebben bij de enumeratie van state geen waarde "finished" maar wel "canceled". Dat doen?

**Comment by roelgrif** [comment]
ik herinner me meer de interpretatie finished = gestopt, canceled = geannuleerd, nooit begonnen (administratieve verwijdering)

**Comment by hamrt** [comment]
Met laatste fix zou de hele issue afgerond moeten zijn. Extra vraag: is additional time relevant op person niveau? Want dit kan potentieel verschillen per toets lijkt me. Voor nu is het meegenomen.

**Comment by rrutte** [comment]
additional time op studentniveau zegt idd niets, maar kunnen we voorlopig laten staan. De hoeveelheid extra tijd is nl afhankelijk van het soort toets en de lengte van de toets.

**Comment by roelgrif** [comment]
Heb ik het nou verkeerd begrepen: we zouden additionalTimeInMin toch juist weghalen, omdat die ten onrechte toegevoegd was?

**Comment by JosVanderArend** [comment]
Goed punt. Wij hebben dit attribuut additionalTimeInMin binnen de consumer van Person weggehaald!

**Comment by JosVanderArend** [comment]
Getest en goed doorgevoerd in YAML!
