### ISSUE TITLE
Consistentie in verwijzingen in consumer van ComponentOfferingAssociation

### ISSUE THREAD

**Issue by JosVanderArend** [NetwerkExamineringDigitalisering/NED-OOAPI#80]
In flow 1 en in de YAML zijn in de consumer van ComponentOfferingAssociationde drie attributen gedefinieerd:
programOfferingAssociationID
courseOfferingAssociationID
orgAssociationId
De eerste twee (met ID) zijn niet consistent met de laatste en zoals het elders wordt toegepast (met Id). 
Ik stel voor deze twee te wijzigen in:
programOfferingAssociationId
courseOfferingAssociationId

**Comment by rrutte** [comment]
@JosVanderArend Mee eens.

**Comment by roelgrif** [comment]
Ook mee eens. Maar in de documentatie heten ze nu nog programOfferingAssociation en courseOfferingAssociation, of is dat in versie 0.9 al gewijzigd? Zou ik die dan mogen ontvangen?

**Comment by JosVanderArend** [comment]
@roelgrif, ik stuur jullie vandaag nog de laatste status van deze versie 0.9, waarschijnlijk aan het begin van de middag!

**Comment by hamrt** [comment]
YAML na lopen op ID vs Id
