### ISSUE TITLE
Consistentie in query parameters

### ISSUE THREAD

**Issue by JosVanderArend** [NetwerkExamineringDigitalisering/NED-OOAPI#81]
In flow 0 Toetscatalogus hebben we in flow 0 en het document bij GET /components als query parameter gedefinieerd 'type=test'.
Consistent met elders zou zijn 'componentType=test'

**Comment by rrutte** [comment]
mee eens. overal waar je op filtert, ook bij offeringType bijvoorbeeld gebruiken we volledige "offeringType" = "component". Zelfde zou hier ook moeten gelden. "componentType"="test"

**Comment by JosVanderArend** [comment]
In het specificatiedocument is dit inmiddels aangepast; nu in flow 0 nog...

**Comment by hamrt** [comment]
issue zit hier: https://github.com/NetwerkExamineringDigitalisering/NED-OOAPI/blob/main/doc/flow0.md#:~:text=%23GET/components%3Ftype%3Dtest

**Comment by JosVanderArend** [comment]
Fixed
