### ISSUE TITLE
attribuut startUpURL ontbreekt in flow 1

### ISSUE THREAD

**Issue by JosVanderArend** [NetwerkExamineringDigitalisering/NED-OOAPI#82]
In flow 3 wordt attribuut startUpURL (in Consumer van ComponentOfferingAssociation) gebruikt. Ik zie dit attribuut niet in flow 1 genoemd, terwijl dit gegeven wel vanuit Deelnemerregistratie (SIS) moet komen, toch?

Zo ja, dan ontbreekt dit attribuut startUpURL (in Consumer van Association) in betreffende diagrammen en examples

**Comment by roelgrif** [comment]
Volgens mij doen we er in flow 1 niets mee. We leveren wel een accountId maar de startup URL is iets tussen TPS en TA volgens mij.

**Comment by hamrt** [comment]
Klopt is alleen vanuit tps. Is mogelijk zelfs heel persoonsspecfiek.Verstuurd vanaf mijn iPhoneOp 21 jul. 2023 om 12:24 heeft Roel Griffioen ***@***.***> het volgende geschreven:﻿
Volgens mij doen we er in flow 1 niets mee. We leveren wel een accountId maar de startup URL is iets tussen TPS en TA volgens mij.

**Comment by JosVanderArend** [comment]
Dan is dit niet relevant en sluit ik dit issue
