### ISSUE TITLE
Gebruik van namen van student.

### ISSUE THREAD

**Issue by rrutte** [NetwerkExamineringDigitalisering/NED-OOAPI#84]
Vanmiddag in DEUG overleg kwam de naam van de student nog even langs. Hoe je deze het liefst gaat vullen is als:

person.givenName -> formele voornamen
person.preferredName -> voorkeursvoornaam
person.surnamePrefix -> voorkeursachternaamtussenvoegsels
person.surname -> voorkeursachternaam
person.displayName -> Geboorteachternaam, formele voornamen geboortenaamtussenvoegsels

Hierbij worden de voorkeursnamen gebruikt om in de verschillende applicaties te tonen en de displayName op de presentielijst.

Als die person.displayName niet op deze manier gebruikt kan worden stellen we voor om een attribuut hiervoor op te nemen in de consumer die we nu hebben, bijvoorbeeld idCheckName

**Comment by hamrt** [comment]
Dat zou dan voor nu in consumer moeten.Verstuurd vanaf mijn iPhoneOp 21 jul. 2023 om 13:38 heeft rrutte ***@***.***> het volgende geschreven:﻿
Vanmiddag in DEUG overleg kwam de naam van de student nog even langs. Hoe je deze het liefst gaat vullen is als:
person.givenName -> formele voornamen
person.preferredName -> voorkeursvoornaam
person.surnamePrefix -> voorkeursachternaamtussenvoegsels
person.surname -> voorkeursachternaam
person.displayName -> Geboorteachternaam, formele voornamen geboortenaamtussenvoegsels
Hierbij worden de voorkeursnamen gebruikt om in de verschillende applicaties te tonen en de displayName op de presentielijst.
Als die person.displayName niet op deze manier gebruikt kan worden stellen we voor om een attribuut hiervoor op te nemen in de consumer die we nu hebben, bijvoorbeeld idCheckName

**Comment by roelgrif** [comment]
Op zich eens met het requirement dat we beide naam typen nodig hebben, dus bij voorbaat akkoord met een extra displayName in de consumer. Wat ik me wel afvraag is of het 'wisselen' van het gebruik van surname (van geboortenaam naar 'gebruiks'-achternaam / voorkeursachternaam) niet strijdig is met wat er in pilot 1 / flow 2/3/4 al is gebouwd (er staat nu in de documentatie dat de surname de geboortenaam is). Ik ga op 13 augustus kijken wat hier uit is gekomen en dan zullen we het aanpassen wat er nu gebouwd is.

**Comment by hamrt** [comment]
Nog aan passen en sluiten:
idCheckName toeveogen in consumers
displayName afspraak vullen met preferred + prefix + surname

**Comment by hamrt** [comment]
er staat idCheck moet idCheckName worden!

**Comment by roelgrif** [comment]
Bijna.
Er moet ook nog een tussenvoegsel achter de voornamen, + de student primary code (achter nog weer een komma). Vergelijkbaar met displayname, met dit verschil dat displayname nu de algemeen gebruikte naam bevat, en de idCheckName de formele naam volgens het BRP. Zie ook hieronder:

displayname Tekst 1 Weergavenaam van persoon, die wordt getoond op het computerscherm bij digitale toetsafname.
Toelichting Dit veld bevat een aaneenrijging van de naamgegevens van de persoon. 
Bij voorkeur de waarden in deze volgorde, gescheiden door komma en spatie (tussen givenName en surnamePrefix 
alleen spatie): surname, givenName, surnamePrefix, code (uit primaryCode).

**Comment by JosVanderArend** [comment]
@roelgrif , @hamrt en ik hebben in onderling overleg besloten dit toch voorlopig nog zo te laten als ik eerder voorstelde, dus bijvoorbeeld: "van der Graaf, Jacobus Adrianus". 

Omdat dit exact is zoals vermeld op het legitimatiebewijs: het deel voor de komma is naamdeel 1 (NAAM) en het deel na de komma is naamdeel 2 (VOORNAMEN).
Wat zou het nut zijn van het studentnummer m.b.t. legitimatie?

**Comment by roelgrif** [comment]
Snap ik maar het nadeel is wel dat het niet op achternaam sorteerbaar is.
Ik weet niet of voor de legitimatie altijd paspoort of ID of rijbewijs gebruikt wordt. Als de instelling een eigen studentenpas heeft dan zal daar het studentnummer op staan.

**Comment by JosVanderArend** [comment]
@rrutte en @boerrookhuiszen, is er in idCheckName (naam zoals op legitiatmatie) behoefte aan een studentnummer?

**Comment by JosVanderArend** [comment]
@roelgrif, maar je kunt het hiermee toch precies sorteren op NAAM (voorvoegsel en achternaam) zoals dat op de legitimatie staat?

**Comment by roelgrif** [comment]
Dat wel, maar als ik van der Arend zou heten, zou ik verwachten mijn tafel in een alfabetisch geordende examenzaal te kunnen vinden bij de A en niet bij de V. Toch?

**Comment by JosVanderArend** [comment]
Ik zou daar dan wel de voorkeursachternaam (surname of diisplayName) verwachten (en niet die van het paspoort). 

Ik begrijp dat je met de namen zoals op het legitimatiebewijs (idCheckName) toch meer dingen wilt doen dan het controleren van de identiteit!

**Comment by roelgrif** [comment]
Ik begeef me wellicht op het gebied waarin ik geen expert (meer) ben, maar toen ik nog VAVO docent was en we gingen examens doen controleerde ik de identiteit door langs de tafels te lopen en de afgedrukte officiele naam te vergelijken met het door de student opengeslagen paspoort dat ook op die tafel lag.

**Comment by roelgrif** [comment]
Hm ... de student number stond er dus toch al wel bij, zie onder (in het word-document zelfs zowel bij displayName als bij idCheckName). Ik wacht maar even met weghalen dus. Graag toch in ieder geval (los van het weghalen van het student number) een beter voorbeeld: "Graaf, Jacobus Adrianus van der" of zo.

idCheckName:
    type: string
    description: | 
      The name of the person as printed on the official identification documents (Driver's license or passport or id card)
      This MUST be formatted as "surname prefix surname, given names"  (separating surnamePrefix and surname with a single space and surname and given names by a comma and space) 
      If the surname or given names are not available or secret the value of "secret" and "notAvailable" are recommended, surname prefix can be omitted.
      E.g. "van der Graaf, Jacobus Adrianus"
      Optionally the value of the student number can be added to this field by adding this at the end separated by a comma.
      E.g. "van der Graaf, Jacobus Adrianus, s12345678"

**Comment by hamrt** [comment]
to be added to 0.91 documentation @JosVanderArend

**Comment by JosVanderArend** [comment]
Beide tekststrings displayName en idCheckName hebben nu dezelfde opbouw: achternaam en roepnaam/voornamen (eventueel aangevuld met voorvoegsel) in documentatie 0.9.1.
