### ISSUE TITLE
Flow 1 and flow 2,3 status update

### ISSUE THREAD

**Issue by rrutte** [NetwerkExamineringDigitalisering/NED-OOAPI#85]
Op basis van volledige programOfferingAssociation heb ik een voorbeeld gemaakt in flow 1 [https://github.com/NetwerkExamineringDigitalisering/NED-OOAPI/blob/main/doc/flow1.md#flow-2b-2-example-of-provisioning-current-program-associations-information](https://github.com/NetwerkExamineringDigitalisering/NED-OOAPI/blob/main/doc/flow1.md#flow-2b-2-example-of-provisioning-current-program-associations-information)

Daarnaast levert het gebruik van flow 2 (PUT .../offering/{offeringId}  nog niet altijd de gewenste toetsmomentconfiguratie op in Remindo

**Comment by hamrt** [comment]
PUT query parameters moeten weg!! 
hernoemen van de kopjes in FLOW 1 zodat ze mee lopen nu staat flow2 als tekst in flow 1 dat is verwarrend

**Comment by hamrt** [comment]
@rrutte kun je het probleem mbt remindo duiden? ligt het aan de definitie of aan de implementatie (voor dat laatste hier niet opnemen)
