### ISSUE TITLE
Generate spec.yaml for this project

### ISSUE THREAD

**Issue by mcginkel** [NetwerkExamineringDigitalisering/NED-OOAPI#9]

**Comment by boerrookhuiszen** [comment]
To get started, I copied the official OOAPI v5 spec and commented out some irrelevant parts, see PR https://github.com/NetwerkExamineringDigitalisering/NED-OOAPI/pull/14

**Comment by JosVanderArend** [comment]
Ja, ik zie de specs.yaml met de ongebruikte delen als commentaar gemaakt

**Comment by mcginkel** [comment]
ik voeg nog de consumers toe. @JosVanderArend
