### ISSUE TITLE
Zijn Program en Course ook voor medewerkers?

### ISSUE THREAD

**Issue by JosVanderArend** [NetwerkExamineringDigitalisering/NED-OOAPI#90]
Er zijn nu in flow 1 extra objecten gespecificeerd om meer achtergrond van de student over de opleiding en het opleidingsprogramma (ProgramOffering en Program) en over het opleidingsdeel en deelprogramma (CourseOffering en Course) over te kunnen dragen. Allemaal direct of indirect gekoppeld aan de Planbare toets (ComponentOffering) via een Toetsinschrijving (ComponentOfferingAssociation).

Voor een medewerker hebben we ook de mogelijkheid om deze te koppelen aan de Planbare toets (ComponentOffering) via een Toetsinschrijving (ComponentOfferingAssociation). Hebben we voor de medewerker ook deze achtergrondinformatie nodig in ProgramOffering, Program, CourseOffering en Course?
Zo ja, waar dient dit voor want de rol in de relatie gaat over de Planbare toets?
Zo nee, zouden we deze achtergrondinformatie expliciet moeten verbieden voor medewerkers?

**Comment by roelgrif** [comment]
Ik zie daar vooralsnog geen meerwaarde in. I.p.v. verbieden kunnen we ook expliciet melden 'negeren wanneer gevuld voor een niet-student' of zoiets. Er is tenslotte niemand die sancties oplegt bij overtreding. En om het bericht nou af te gaan keuren als hier onverhoopt toch wat in staat gaat m.i. (te) ver.

**Comment by JosVanderArend** [comment]
In het specificatiedocument is dit nu duidelijker gemaakt door bij CourseOfferingAssociation en ProgramOfferingAssociation expliciet te vermelden dat dit om een inschrijving van de student gaat.

**Comment by JosVanderArend** [comment]
@hamrt , ook in flow 1?
