### ISSUE TITLE
Flow 5 PUT of PATCH?

### ISSUE THREAD

**Issue by rrutte** [NetwerkExamineringDigitalisering/NED-OOAPI#92]
We hebben met de laatste aanpassing voor ondersteuning meerdere pogingen in flow 5 de methode van PATCH naar PUT gewijzigd. Echter, bij een PUT zijn natuurlijk wel een attributen verplicht die op dat moment wel meegenomen moeten worden. We hebben twee opties:

PUT (inclusief verplichte attributen op association)
PATCH (zonder verplichte attributen op association)

**Comment by roelgrif** [comment]
Ik zou denken dat resultaten op een eerder aangeleverde association het makkelijkste via een PATCH teruggeleverd kunnen worden, terwijl nieuw aangemaakte pogingen beter met een PUT kunnen. Moeten we per se kiezen?

**Comment by hamrt** [comment]
Normale flow:
Wanneer de resultaten van een bestaande poging, aangeleverd door het SIS richting TPS in flow 1, worden teruggestuurd in flow 5 wordt gebruik gemaakt van een PATCH
Extra poging flow (vanuit TPS)
Wanneer een extra poging wordt gecreëerd door het TPS wordt in flow 5 een PUT gedaan richting het SIS voor de betreffende association

**Comment by JosVanderArend** [comment]
@hamrt , ik heb flow 5 verbouwd tot 2 information flows: 5.1 Test result en 5.2 Attempt result. 
Wil jij dit reviewen en zo nodig verbeteren?

**Comment by hamrt** [comment]
@JosVanderArend done
