### ISSUE TITLE
patch offerings en associations zonder context.

### ISSUE THREAD

**Issue by rrutte** [NetwerkExamineringDigitalisering/NED-OOAPI#93]
voor flow 1 hebben we een aantal patch methodes op offerings en associations. Echter, dit kunnen offerings binnen verschillende contexten zijn tussen een SIS en een planningssysteem. Program, component en later ook course.

Mijn voorstel is om in patch calls tussen SIS en planning altijd de context mee te geven, dus:

- offerings: offeringType
- associations: associationType

zodat het ontvangende systeem weet wat voor soort offering/association het betreft en daardoor ook het juiste pad kan kiezen om de patch te verwerken.

**Comment by hamrt** [comment]
besluit om de Type varianten in de payload mee te nemen in de PATCH

**Comment by JosVanderArend** [comment]
Ik heb dit inmiddels in het specificatiedocument verwerkt

**Comment by hamrt** [comment]
Voorstel is dan om de type velden per object (offering en association) te verplichten en op te nemen in de te maken voorbeelden van flow1

**Comment by roelgrif** [comment]
Wat mij betreft OK.

**Comment by JosVanderArend** [comment]
@roelgrif, nog een controlevraag: 
Moet dit attribuut associationType ook in de PATCH /associations/{associationId} van flow 5 verplicht meekomen?
Ik denk zelf van niet want dit koppelvlak ligt bij het SIS en daar worden geen andere type associations aangeboden.

**Comment by rrutte** [comment]
> Voorstel is dan om de type velden per object (offering en association) te verplichten en op te nemen in de te maken voorbeelden van flow1

Wat mij betreft ook OK

**Comment by JosVanderArend** [comment]
In alle PATCH-berichten voor offering en association is het type (in offeringType of associationType) verplicht!
