### ISSUE TITLE
het grote groepen issue 

### ISSUE THREAD

**Issue by hamrt** [NetwerkExamineringDigitalisering/NED-OOAPI#94]
Wat te doen met groepen? 
Te bediscussieren oa
Duur lidmaatschappen
Duur van bestaan van groep

**Comment by rrutte** [comment]
Belangrijkste wat je wilt bereiken is dat je weet wie, wanneer in welke hoedanigheid lid van de groep wordt/is/geweest is, terwijl je de mogelijkheid wilt behouden om ad-hoc de huidige/actuele groepsdeelnames op te kunnen vragen.

Op zich zou je er al zijn als je er al zijn om een gelijkaardig object als association te introduceren. In dat geval zou je het volgende krijgen:

GroupMembership

- membershipId: UUID
- membershipType: associationType
- role: associationRole
- state: state
- consumers: Consumer[ ]
- ext: ext
- person: Person
- group: Group

Het is het overwegen waard om start- en enddate van de membership op te nemen, maar consequentie daarvan is dat je niet meer in sync bent met de wijze waarop association is gemodelleerd. 

In het voorbeeld heb ik state, associationType en associationRole gebruikt als types omdat die overeenkomen met de wijze waarop ze in association gemodelleerd zijn.

Op basis van de modelkeuze volgt natuurlijk de vraag welke api's je hierop wilt gaan definiëren.

**Comment by roelgrif** [comment]
voor onze doeleinden zouden die start- en enddate er zeker bij moeten. Het lastige is wel dat iemand in een groep kan komen, er dan weer uit gaat, en vervolgens er nog eens in komt. Dan kun je natuurlijk alleen die laatste als start date zetten en de end date wissen ... maar het alternatief is een state_date introduceren als extra sleutel, dan kan je dit krijgen:
UUID = x, state_date = 1-8-2021, state = active
UUID = x, state_date = 1-8-2022, state = inactive/canceled
UUID = x, state_date = 1-8-2023, state = active
Dat vergt wel veel interpretatiewerk aan de ontvangende kant (vanuit ons gezien staat het al zo in de tabel :) )

membershipType: associationType --> dat zie ik nog niet helemaal voor me. Zou je dan in de enum groupAssociation moeten opnemen? maar associationType hoort eigenlijk alleen bij offerings. Dus dan is een groupOffering logischer ertussenin ... wellicht toch membership maar los modelleren van associations.

**Comment by hamrt** [comment]
Op groups moet op het membership endpoint ook een peildatum mee kunnen krijgen. Zodat de actieve en toekomstig actieve leden op een moment kan worden meegegeven. Voorkeur om mensen die inactive zij niet meer door te geven
Since until voor membership om aan te geven binnen welke periode het overzicht van leden moet worden gegeven. Zonder since until kiezen we er voor om de huidige datum als peildatum op te nemen. 
We kiezen er voor om niet met een status te werken maar om wel per groepslid aan te geven wat de geldigheid is van het lidmaatschap (startDate en endDate op het lidmaatschap)
Als er een startDatum bekend is moet die mee gegeven worden. De einddatum kan in principe leeg zijn.

**Comment by hamrt** [comment]
Als er geen startDatum bekend is word de datum van vandaag toegepast als endDate wordt gekozen voor **tot en met** de datum die wordt doorgegeven

**Comment by hamrt** [comment]
Xshedule
"StudentenLidVan": [
                {
                    "StudentId": 1796673,
                    "Gedurende": [
                        {
                            "From": "2023-09-04T08:30:00",
                            "To": "2024-06-07T17:00:00"
                        }
                    ],
					
					
					
PeopleSoft
"StudentenLidVan": [

                {

                    "StudentId": 1796673,

                    "status": [

                        {

                            "From": "2023-09-04T08:30:00",

                            "Status": "active"

                        },   {

                            "From": "2023-09-08T08:30:00",

                            "Status": "canceled"

                        }

                    ]

**Comment by hamrt** [comment]
opgelost met nieuwe endpoint voor memberships op groups en membership item als object
