### ISSUE TITLE
Spelfoutje in Flow0?

### ISSUE THREAD

**Issue by joeldebruijn** [NetwerkExamineringDigitalisering/NED-OOAPI#95]
Staat er een spelfoutje in Flow 0 : "request catalogue from toetsafname applicatie"
https://github.com/NetwerkExamineringDigitalisering/NED-OOAPI/blob/77d9590f3c2500a29997445d31f38ed1c580a4c3/doc/flow0.md

![afbeelding](https://github.com/NetwerkExamineringDigitalisering/NED-OOAPI/assets/3906940/6e356adc-19a8-4228-98ba-8c7f37c289fd)

comonentType ipv componentType?

**Comment by JosVanderArend** [comment]
Inderdaad, het is inmiddels gecorrigeerd.
Dank voor het melden.
@joeldebruijn , Wil je dit issue afsluiten als de aanpassing correct is?

**Comment by joeldebruijn** [comment]
Duurt het even eer dat het doorwerkt of klopt het dat het nog steeds zo staat?:

![afbeelding](https://github.com/NetwerkExamineringDigitalisering/NED-OOAPI/assets/3906940/d6434a9d-b464-4a18-b45b-fe33ac888ef1)

**Comment by JosVanderArend** [comment]
Bij mij was en is het al wel gewijzigd:
![afbeelding](https://github.com/NetwerkExamineringDigitalisering/NED-OOAPI/assets/36879018/3e4cc57a-2f40-4859-a5ee-deb27dcfbf95)

**Comment by hamrt** [comment]
gefixed

**Comment by JosVanderArend** [comment]
@joeldebruijn het verschil komt doordat jij in een andere branch dan main kijkt.
Zie hier voor de juiste link: https://github.com/NetwerkExamineringDigitalisering/NED-OOAPI/blob/main/doc/flow0.md
