### ISSUE TITLE
Startdate of startdatetime op offerings?

### ISSUE THREAD

**Issue by rrutte** [NetwerkExamineringDigitalisering/NED-OOAPI#96]
Volgens OOAPI V5 heeft de offering attributen startDate en endDate. Binnen OKE gebruiken we startDateTime en endDateTime. Dit conflicteert met elkaar. Wordt OOAPI V5 hierop aangepast of moeten we ons hier conformeren aan OOAPI V5?

**Comment by roelgrif** [comment]
Volgens mij gebruiken we binnen de componentOffering startDateTime en endDateTime (dit is destijds al bij de vaststelling van flow 2/3/4 zo vastgesteld dacht ik?), maar binnen de courseOffering en programOffering startDate en endDate. Merkwaardig inderdaad omdat deze attributen in het 'gemeenschappelijke deel' van de offering zitten. Een aanpassing naar dateTime heeft dus ook (wat mij betreft ongewenste) gevolgen voor de course/programOffering.

**Comment by JosVanderArend** [comment]
Ik zie dat het specificatiedocument niet correct is: attirbuten startDateTime en endDateTime zijn verplicht (nu optioneel). Wordt gecorrigeerd!

**Comment by hamrt** [comment]
dit punt zou voor een volgende versie makkelijker gemaakt moeten worden door bijvoorbeeld een specifiek endpoint te maken courseOffering of door verplichte velden overall gelijk te trekken.
