### ISSUE TITLE
Binnenkomende calls onderscheiden per TPS

### ISSUE THREAD

**Issue by roelgrif** [NetwerkExamineringDigitalisering/NED-OOAPI#97]
Op ons integratieplatform kunnen we meerdere TPS-sen bedienen en voor elk de eigen authenticatie verzorgen/controleren.
Daarna komt de GET call bij onze applicatie aan. Daar is intussen de authenticatie header informatie (bearer-token) niet meer beschikbaar, die is inmiddels door het integratieplatform verwijderd. Kortom, we weten daar niet welk TPS er associations, persons of offerings opvraagt. Als er een ID meegegeven wordt kunnen we nog wel nagaan welke info teruggeleverd moet worden, elk TPS heeft zijn eigen set aan offering ID's, person ID's en association ID's en de kans is astronomisch klein dat een TPS zomaar een ID opvraagt die bij een ander TPS hoort. Echter: er kan ook een serie offerings opgevraagd worden en dan weten we niet of we de OnTrac set moeten leveren of de set van (hypothetisch ander/toekomstig TPS). Hoe is dit op te lossen? Extra header attribute? een query parameter?

**Comment by hamrt** [comment]
Oplossing voor het doorsturen van deze gegevens is het plaatsen van de gegevens in de header na dat het via het integratieplatform binnen is gekomen. Verder onderzoeken hoe dit past binnen de eduKoppeling oAuth oplossing. Is het bijvoorbeeld to en from gebaseerd zijn op applicatie + instelling alleen onderwijs instelling si hierbij niet voldoende.

**Comment by hamrt** [comment]
@JosVanderArend contact leggen met Brian en eduKoppeling

**Comment by JosVanderArend** [comment]
In aanloop naar het contactmoment (mogelijk dinsdag 3 oktober) alvast de voorbereidende informatie. 
Het conceptvoorstel van het betreffende profiel "Secure API OAuth Client Credentials profielen" is beschreven in het volgende document: https://www.edustandaard.nl/app/uploads/2023/07/2023-07-24-Edukoppeling-Secure-API-OAuth-Client-Credentials-profielen-v0.8.pdf. 
De totale afspraak Edukoppeling rondom dit profiel is hier beschreven: https://www.edustandaard.nl/standaard_afspraken/edukoppeling-transactiestandaard/edukoppeling-juli-2023/.
