### ISSUE TITLE
Opleidingscode (of mbo-niveau) nodig in Toetsafname

### ISSUE THREAD

**Issue by JosVanderArend** [NetwerkExamineringDigitalisering/NED-OOAPI#99]
In flow 1 is expliciet beschreven hoe de opleidingscode (voorheen crebocode) in de contextinformatie van de student in flow 1 wordt meegegeven. Deze opleidingscode is onderdeel van het opleidingsprogramma (Program). Dit gegeven opleidingscode is geen onderdeel van flow 2 omdat dit niet nodig is geacht.

Facet (DUO) zegt dit gegeven nodig te hebben om onderscheid in normering te kunnen maken bij de afname van een toets voor verschillende niveaus, bijvoorbeeld voor een hoger niveau en 'strakkere normering' dan voor een lager niveau.
In en eerste reactie lijkt voor dit doeleinde het betreffende mbo-niveau van de opleiding (het opleidingsprogramma) beter passend. En misschien is dit ook nog wel beter omdat er opleidingscodes zijn die geen eenduidig mbo-niveau betreffen, zoals de opleidingscode bij dossier of domein. 

Facet (DUO) onderzoekt nog de nadere doelbinding van dit gegeven opleidingscode (of mbo-niveau) en rapporteert hierover terug.

**Comment by hamrt** [comment]
Op dit moment zijn MBO-niveau en CREBO (als verplicht) velden die mee moeten komen. De vraag is in hoeverre deze informatie werkelijk nodig is. @JosVanderArend neemt contact op met FB van Facet

**Comment by hamrt** [comment]
verder onderzoek in het kader van #28 voor nu aflsuiten
